// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
)

type ApprovalToken struct {
	TokenHash         string         `json:"token_hash"`
	TaskID            string         `json:"task_id"`
	TraceID           string         `json:"trace_id"`
	Tool              string         `json:"tool"`
	ApprovedBytesHash string         `json:"approved_bytes_hash"`
	MintedAt          string         `json:"minted_at"`
	ExpiresAt         string         `json:"expires_at"`
	ConsumedAt        sql.NullString `json:"consumed_at"`
}

type AutonomyState struct {
	Tool                 string `json:"tool"`
	Class                string `json:"class"`
	Scope                string `json:"scope"`
	Level                int64  `json:"level"`
	ConsecutiveApprovals int64  `json:"consecutive_approvals"`
	UpdatedAt            string `json:"updated_at"`
}

type Chunk struct {
	ID          int64  `json:"id"`
	EpisodeID   int64  `json:"episode_id"`
	Seq         int64  `json:"seq"`
	Text        string `json:"text"`
	ContentHash string `json:"content_hash"`
	CreatedAt   string `json:"created_at"`
}

type Entity struct {
	ID            int64          `json:"id"`
	CanonicalName string         `json:"canonical_name"`
	Kind          sql.NullString `json:"kind"`
	Status        string         `json:"status"`
	CreatedAt     string         `json:"created_at"`
}

type EntityAlias struct {
	ID        int64  `json:"id"`
	EntityID  int64  `json:"entity_id"`
	Alias     string `json:"alias"`
	CreatedAt string `json:"created_at"`
}

type Episode struct {
	ID         int64          `json:"id"`
	Source     string         `json:"source"`
	SourcePath sql.NullString `json:"source_path"`
	SourceHash sql.NullString `json:"source_hash"`
	SourceTier string         `json:"source_tier"`
	StartedAt  sql.NullString `json:"started_at"`
	EndedAt    sql.NullString `json:"ended_at"`
	Status     string         `json:"status"`
	Meta       sql.NullString `json:"meta"`
	CreatedAt  string         `json:"created_at"`
}

type Event struct {
	ID        int64  `json:"id"`
	TraceID   string `json:"trace_id"`
	Ts        string `json:"ts"`
	Kind      string `json:"kind"`
	Payload   string `json:"payload"`
	CreatedAt string `json:"created_at"`
}

type Evidence struct {
	ID        int64          `json:"id"`
	FactID    int64          `json:"fact_id"`
	EpisodeID sql.NullInt64  `json:"episode_id"`
	SessionID sql.NullString `json:"session_id"`
	Polarity  int64          `json:"polarity"`
	CreatedAt string         `json:"created_at"`
}

type Fact struct {
	ID            int64          `json:"id"`
	Subject       string         `json:"subject"`
	Predicate     string         `json:"predicate"`
	Object        string         `json:"object"`
	SourceTier    string         `json:"source_tier"`
	Evidentiality string         `json:"evidentiality"`
	Confidence    float64        `json:"confidence"`
	Importance    float64        `json:"importance"`
	ValidFrom     sql.NullString `json:"valid_from"`
	ValidTo       sql.NullString `json:"valid_to"`
	Status        string         `json:"status"`
	Evidence      sql.NullString `json:"evidence"`
	ExtractorVer  sql.NullString `json:"extractor_ver"`
	UpdatedAt     string         `json:"updated_at"`
	CreatedAt     string         `json:"created_at"`
}

type MergeLedger struct {
	ID          int64          `json:"id"`
	Op          string         `json:"op"`
	SrcEntityID sql.NullInt64  `json:"src_entity_id"`
	DstEntityID sql.NullInt64  `json:"dst_entity_id"`
	Evidence    sql.NullString `json:"evidence"`
	Actor       string         `json:"actor"`
	CreatedAt   string         `json:"created_at"`
}

type Outbox struct {
	ID           int64          `json:"id"`
	TraceID      string         `json:"trace_id"`
	Kind         string         `json:"kind"`
	Payload      string         `json:"payload"`
	DispatchedAt sql.NullString `json:"dispatched_at"`
	CreatedAt    string         `json:"created_at"`
}

type Task struct {
	ID        string         `json:"id"`
	TraceID   string         `json:"trace_id"`
	SessionID sql.NullString `json:"session_id"`
	State     string         `json:"state"`
	TaintTier string         `json:"taint_tier"`
	Model     sql.NullString `json:"model"`
	Envelope  sql.NullString `json:"envelope"`
	UpdatedAt string         `json:"updated_at"`
	CreatedAt string         `json:"created_at"`
}

type UndoWindow struct {
	ID       int64  `json:"id"`
	TaskID   string `json:"task_id"`
	Tool     string `json:"tool"`
	TraceID  string `json:"trace_id"`
	OpenedAt string `json:"opened_at"`
	Deadline string `json:"deadline"`
	State    string `json:"state"`
}
