// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
)

type AnchorLog struct {
	ID         int64          `json:"id"`
	EventID    int64          `json:"event_id"`
	DigestHex  string         `json:"digest_hex"`
	AnchoredAt string         `json:"anchored_at"`
	RemoteRef  sql.NullString `json:"remote_ref"`
	Status     string         `json:"status"`
}

type ApprovalToken struct {
	TokenHash         string         `json:"token_hash"`
	TaskID            string         `json:"task_id"`
	TraceID           string         `json:"trace_id"`
	Tool              string         `json:"tool"`
	Class             string         `json:"class"`
	Scope             string         `json:"scope"`
	ApprovedBytesHash string         `json:"approved_bytes_hash"`
	MintedAt          string         `json:"minted_at"`
	ExpiresAt         string         `json:"expires_at"`
	ConsumedAt        sql.NullString `json:"consumed_at"`
}

type AutonomyState struct {
	Tool                 string `json:"tool"`
	Class                string `json:"class"`
	Scope                string `json:"scope"`
	Level                int64  `json:"level"`
	ConsecutiveApprovals int64  `json:"consecutive_approvals"`
	UpdatedAt            string `json:"updated_at"`
}

type Chunk struct {
	ID          int64  `json:"id"`
	EpisodeID   int64  `json:"episode_id"`
	Seq         int64  `json:"seq"`
	Text        string `json:"text"`
	ContentHash string `json:"content_hash"`
	CreatedAt   string `json:"created_at"`
}

type EgressBudget struct {
	Host  string `json:"host"`
	Day   string `json:"day"`
	Bytes int64  `json:"bytes"`
}

type Entity struct {
	ID            int64          `json:"id"`
	CanonicalName string         `json:"canonical_name"`
	Kind          sql.NullString `json:"kind"`
	Status        string         `json:"status"`
	CreatedAt     string         `json:"created_at"`
}

type EntityAlias struct {
	ID        int64  `json:"id"`
	EntityID  int64  `json:"entity_id"`
	Alias     string `json:"alias"`
	CreatedAt string `json:"created_at"`
}

type Episode struct {
	ID         int64          `json:"id"`
	Source     string         `json:"source"`
	SourcePath sql.NullString `json:"source_path"`
	SourceHash sql.NullString `json:"source_hash"`
	SourceTier string         `json:"source_tier"`
	StartedAt  sql.NullString `json:"started_at"`
	EndedAt    sql.NullString `json:"ended_at"`
	Status     string         `json:"status"`
	Meta       sql.NullString `json:"meta"`
	CreatedAt  string         `json:"created_at"`
}

type Event struct {
	ID        int64  `json:"id"`
	TraceID   string `json:"trace_id"`
	Ts        string `json:"ts"`
	Kind      string `json:"kind"`
	Payload   string `json:"payload"`
	CreatedAt string `json:"created_at"`
}

type Evidence struct {
	ID        int64          `json:"id"`
	FactID    int64          `json:"fact_id"`
	EpisodeID sql.NullInt64  `json:"episode_id"`
	SessionID sql.NullString `json:"session_id"`
	Polarity  int64          `json:"polarity"`
	CreatedAt string         `json:"created_at"`
}

type Fact struct {
	ID            int64          `json:"id"`
	Subject       string         `json:"subject"`
	Predicate     string         `json:"predicate"`
	Object        string         `json:"object"`
	SourceTier    string         `json:"source_tier"`
	Evidentiality string         `json:"evidentiality"`
	Confidence    float64        `json:"confidence"`
	Importance    float64        `json:"importance"`
	ValidFrom     sql.NullString `json:"valid_from"`
	ValidTo       sql.NullString `json:"valid_to"`
	Status        string         `json:"status"`
	Evidence      sql.NullString `json:"evidence"`
	ExtractorVer  sql.NullString `json:"extractor_ver"`
	UpdatedAt     string         `json:"updated_at"`
	CreatedAt     string         `json:"created_at"`
}

type LedgerDigestState struct {
	ID          int64  `json:"id"`
	LastEventID int64  `json:"last_event_id"`
	Digest      []byte `json:"digest"`
}

type MergeLedger struct {
	ID          int64          `json:"id"`
	Op          string         `json:"op"`
	SrcEntityID sql.NullInt64  `json:"src_entity_id"`
	DstEntityID sql.NullInt64  `json:"dst_entity_id"`
	Evidence    sql.NullString `json:"evidence"`
	Actor       string         `json:"actor"`
	CreatedAt   string         `json:"created_at"`
}

type Outbox struct {
	ID           int64          `json:"id"`
	TraceID      string         `json:"trace_id"`
	Kind         string         `json:"kind"`
	Payload      string         `json:"payload"`
	DispatchedAt sql.NullString `json:"dispatched_at"`
	CreatedAt    string         `json:"created_at"`
	AvailableAt  sql.NullString `json:"available_at"`
	LeaseUntil   sql.NullString `json:"lease_until"`
	Attempts     int64          `json:"attempts"`
}

type PendingApproval struct {
	ID                string         `json:"id"`
	TaskID            string         `json:"task_id"`
	TraceID           string         `json:"trace_id"`
	Tool              string         `json:"tool"`
	Class             string         `json:"class"`
	Scope             string         `json:"scope"`
	ApprovedBytesHash string         `json:"approved_bytes_hash"`
	MintedAt          string         `json:"minted_at"`
	ExpiresAt         string         `json:"expires_at"`
	ConsumedAt        sql.NullString `json:"consumed_at"`
	ToolInput         []byte         `json:"tool_input"`
}

type SessionTaint struct {
	SessionID string         `json:"session_id"`
	Tier      string         `json:"tier"`
	Reason    sql.NullString `json:"reason"`
	UpdatedAt string         `json:"updated_at"`
}

type Task struct {
	ID             string         `json:"id"`
	TraceID        string         `json:"trace_id"`
	SessionID      sql.NullString `json:"session_id"`
	State          string         `json:"state"`
	TaintTier      string         `json:"taint_tier"`
	Model          sql.NullString `json:"model"`
	Envelope       sql.NullString `json:"envelope"`
	UpdatedAt      string         `json:"updated_at"`
	CreatedAt      string         `json:"created_at"`
	Lane           string         `json:"lane"`
	SecretCategory sql.NullString `json:"secret_category"`
	Status         string         `json:"status"`
	NextRetryAt    sql.NullString `json:"next_retry_at"`
	Attempts       int64          `json:"attempts"`
}

type ToolCall struct {
	ID              int64          `json:"id"`
	TaskID          string         `json:"task_id"`
	Seq             int64          `json:"seq"`
	ToolName        string         `json:"tool_name"`
	Class           string         `json:"class"`
	ArgsHash        string         `json:"args_hash"`
	ApprovalTokenID sql.NullString `json:"approval_token_id"`
	Status          string         `json:"status"`
	ReceiptJson     sql.NullString `json:"receipt_json"`
	StartedAt       sql.NullString `json:"started_at"`
	FinishedAt      sql.NullString `json:"finished_at"`
	CreatedAt       string         `json:"created_at"`
}

type UndoWindow struct {
	ID       int64  `json:"id"`
	TaskID   string `json:"task_id"`
	Tool     string `json:"tool"`
	TraceID  string `json:"trace_id"`
	OpenedAt string `json:"opened_at"`
	Deadline string `json:"deadline"`
	State    string `json:"state"`
}
