// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const deleteChunksByEpisode = `-- name: DeleteChunksByEpisode :exec
DELETE FROM chunks WHERE episode_id = ?
`

func (q *Queries) DeleteChunksByEpisode(ctx context.Context, episodeID int64) error {
	_, err := q.db.ExecContext(ctx, deleteChunksByEpisode, episodeID)
	return err
}

const getEpisodeByPath = `-- name: GetEpisodeByPath :one
SELECT id, source, source_path, source_hash, source_tier, started_at, ended_at, status, meta, created_at
FROM episodes
WHERE source_path = ?
LIMIT 1
`

func (q *Queries) GetEpisodeByPath(ctx context.Context, sourcePath sql.NullString) (Episode, error) {
	row := q.db.QueryRowContext(ctx, getEpisodeByPath, sourcePath)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.SourcePath,
		&i.SourceHash,
		&i.SourceTier,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
		&i.Meta,
		&i.CreatedAt,
	)
	return i, err
}

const getEpisodeBySourceAndPath = `-- name: GetEpisodeBySourceAndPath :one

SELECT id, source, source_path, source_hash, source_tier, started_at, ended_at, status, meta, created_at
FROM episodes
WHERE source = ? AND source_path = ?
LIMIT 1
`

type GetEpisodeBySourceAndPathParams struct {
	Source     string         `json:"source"`
	SourcePath sql.NullString `json:"source_path"`
}

// W12-04 (corpus indexer) queries below. GetEpisodeByPath above does not
// filter by source, which is fine for callers that only ever use one
// source, but the indexer must scope its hash-compare lookup to
// source='memory_file' specifically (task spec step 3), so it gets its own
// query rather than overloading GetEpisodeByPath's signature.
func (q *Queries) GetEpisodeBySourceAndPath(ctx context.Context, arg GetEpisodeBySourceAndPathParams) (Episode, error) {
	row := q.db.QueryRowContext(ctx, getEpisodeBySourceAndPath, arg.Source, arg.SourcePath)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.SourcePath,
		&i.SourceHash,
		&i.SourceTier,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
		&i.Meta,
		&i.CreatedAt,
	)
	return i, err
}

const getTaskBySession = `-- name: GetTaskBySession :one
SELECT id, trace_id, session_id, state, taint_tier, model, envelope, updated_at, created_at
FROM tasks
WHERE session_id = ?
ORDER BY updated_at DESC
LIMIT 1
`

// Sessions are not currently guaranteed to map to exactly one task row
// (resume/retry may append more), so this returns the most recently
// updated task for the session.
func (q *Queries) GetTaskBySession(ctx context.Context, sessionID sql.NullString) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskBySession, sessionID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TraceID,
		&i.SessionID,
		&i.State,
		&i.TaintTier,
		&i.Model,
		&i.Envelope,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertChunk = `-- name: InsertChunk :one
INSERT INTO chunks (episode_id, seq, text, content_hash, created_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, episode_id, seq, text, content_hash, created_at
`

type InsertChunkParams struct {
	EpisodeID   int64  `json:"episode_id"`
	Seq         int64  `json:"seq"`
	Text        string `json:"text"`
	ContentHash string `json:"content_hash"`
	CreatedAt   string `json:"created_at"`
}

func (q *Queries) InsertChunk(ctx context.Context, arg InsertChunkParams) (Chunk, error) {
	row := q.db.QueryRowContext(ctx, insertChunk,
		arg.EpisodeID,
		arg.Seq,
		arg.Text,
		arg.ContentHash,
		arg.CreatedAt,
	)
	var i Chunk
	err := row.Scan(
		&i.ID,
		&i.EpisodeID,
		&i.Seq,
		&i.Text,
		&i.ContentHash,
		&i.CreatedAt,
	)
	return i, err
}

const insertEpisode = `-- name: InsertEpisode :one
INSERT INTO episodes (source, source_path, source_hash, source_tier, started_at, ended_at, status, meta, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, source, source_path, source_hash, source_tier, started_at, ended_at, status, meta, created_at
`

type InsertEpisodeParams struct {
	Source     string         `json:"source"`
	SourcePath sql.NullString `json:"source_path"`
	SourceHash sql.NullString `json:"source_hash"`
	SourceTier string         `json:"source_tier"`
	StartedAt  sql.NullString `json:"started_at"`
	EndedAt    sql.NullString `json:"ended_at"`
	Status     string         `json:"status"`
	Meta       sql.NullString `json:"meta"`
	CreatedAt  string         `json:"created_at"`
}

func (q *Queries) InsertEpisode(ctx context.Context, arg InsertEpisodeParams) (Episode, error) {
	row := q.db.QueryRowContext(ctx, insertEpisode,
		arg.Source,
		arg.SourcePath,
		arg.SourceHash,
		arg.SourceTier,
		arg.StartedAt,
		arg.EndedAt,
		arg.Status,
		arg.Meta,
		arg.CreatedAt,
	)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.SourcePath,
		&i.SourceHash,
		&i.SourceTier,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
		&i.Meta,
		&i.CreatedAt,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :one

INSERT INTO events (trace_id, ts, kind, payload, created_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, trace_id, ts, kind, payload, created_at
`

type InsertEventParams struct {
	TraceID   string `json:"trace_id"`
	Ts        string `json:"ts"`
	Kind      string `json:"kind"`
	Payload   string `json:"payload"`
	CreatedAt string `json:"created_at"`
}

// Starter query set for W12-02 (HANDOFF S4: Go + sqlc-generated queries).
// Later tasks add more queries to this file as they need them; sqlc
// regenerates the whole package from the union of every *.sql file here.
func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, insertEvent,
		arg.TraceID,
		arg.Ts,
		arg.Kind,
		arg.Payload,
		arg.CreatedAt,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.TraceID,
		&i.Ts,
		&i.Kind,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const insertTask = `-- name: InsertTask :one
INSERT INTO tasks (id, trace_id, session_id, state, taint_tier, model, envelope, updated_at, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, trace_id, session_id, state, taint_tier, model, envelope, updated_at, created_at
`

type InsertTaskParams struct {
	ID        string         `json:"id"`
	TraceID   string         `json:"trace_id"`
	SessionID sql.NullString `json:"session_id"`
	State     string         `json:"state"`
	TaintTier string         `json:"taint_tier"`
	Model     sql.NullString `json:"model"`
	Envelope  sql.NullString `json:"envelope"`
	UpdatedAt string         `json:"updated_at"`
	CreatedAt string         `json:"created_at"`
}

func (q *Queries) InsertTask(ctx context.Context, arg InsertTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, insertTask,
		arg.ID,
		arg.TraceID,
		arg.SessionID,
		arg.State,
		arg.TaintTier,
		arg.Model,
		arg.Envelope,
		arg.UpdatedAt,
		arg.CreatedAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TraceID,
		&i.SessionID,
		&i.State,
		&i.TaintTier,
		&i.Model,
		&i.Envelope,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveMemoryFileEpisodes = `-- name: ListActiveMemoryFileEpisodes :many
SELECT id, source_path FROM episodes
WHERE source = 'memory_file' AND status = 'active'
`

type ListActiveMemoryFileEpisodesRow struct {
	ID         int64          `json:"id"`
	SourcePath sql.NullString `json:"source_path"`
}

func (q *Queries) ListActiveMemoryFileEpisodes(ctx context.Context) ([]ListActiveMemoryFileEpisodesRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveMemoryFileEpisodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveMemoryFileEpisodesRow{}
	for rows.Next() {
		var i ListActiveMemoryFileEpisodesRow
		if err := rows.Scan(&i.ID, &i.SourcePath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChunkIDsByEpisode = `-- name: ListChunkIDsByEpisode :many
SELECT id FROM chunks WHERE episode_id = ? ORDER BY seq ASC
`

func (q *Queries) ListChunkIDsByEpisode(ctx context.Context, episodeID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listChunkIDsByEpisode, episodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByTrace = `-- name: ListEventsByTrace :many
SELECT id, trace_id, ts, kind, payload, created_at
FROM events
WHERE trace_id = ?
ORDER BY id ASC
`

func (q *Queries) ListEventsByTrace(ctx context.Context, traceID string) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByTrace, traceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.TraceID,
			&i.Ts,
			&i.Kind,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEpisodeDeleted = `-- name: MarkEpisodeDeleted :exec
UPDATE episodes
SET status = 'deleted'
WHERE id = ?
`

func (q *Queries) MarkEpisodeDeleted(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markEpisodeDeleted, id)
	return err
}

const updateEpisodeContent = `-- name: UpdateEpisodeContent :exec
UPDATE episodes
SET source_hash = ?, source_tier = ?, status = ?
WHERE id = ?
`

type UpdateEpisodeContentParams struct {
	SourceHash sql.NullString `json:"source_hash"`
	SourceTier string         `json:"source_tier"`
	Status     string         `json:"status"`
	ID         int64          `json:"id"`
}

// Upserts (update half) an existing memory_file episode in place on
// new/changed content: same id, fresh hash/tier, status forced back to
// 'active' (covers the resurrect-a-deleted-file case, not just plain edits).
func (q *Queries) UpdateEpisodeContent(ctx context.Context, arg UpdateEpisodeContentParams) error {
	_, err := q.db.ExecContext(ctx, updateEpisodeContent,
		arg.SourceHash,
		arg.SourceTier,
		arg.Status,
		arg.ID,
	)
	return err
}

const updateTaskSession = `-- name: UpdateTaskSession :exec
UPDATE tasks
SET session_id = ?, updated_at = ?
WHERE id = ?
`

type UpdateTaskSessionParams struct {
	SessionID sql.NullString `json:"session_id"`
	UpdatedAt string         `json:"updated_at"`
	ID        string         `json:"id"`
}

// Persists a worker-reported session_id onto the task row (W12-07 step 3:
// kahyad "persists session_id onto the task row" as the worker's
// {"type":"session",...} stdout line arrives). Session RESUME itself
// (using a stored session_id to continue a LATER task) is W4-02; this
// query only records the value as it arrives.
func (q *Queries) UpdateTaskSession(ctx context.Context, arg UpdateTaskSessionParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskSession, arg.SessionID, arg.UpdatedAt, arg.ID)
	return err
}

const updateTaskState = `-- name: UpdateTaskState :exec
UPDATE tasks
SET state = ?, updated_at = ?
WHERE id = ?
`

type UpdateTaskStateParams struct {
	State     string `json:"state"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateTaskState(ctx context.Context, arg UpdateTaskStateParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskState, arg.State, arg.UpdatedAt, arg.ID)
	return err
}
