// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"
	"database/sql"
)

type Querier interface {
	DeleteChunksByEpisode(ctx context.Context, episodeID int64) error
	GetEpisodeByPath(ctx context.Context, sourcePath sql.NullString) (Episode, error)
	// Sessions are not currently guaranteed to map to exactly one task row
	// (resume/retry may append more), so this returns the most recently
	// updated task for the session.
	GetTaskBySession(ctx context.Context, sessionID sql.NullString) (Task, error)
	InsertChunk(ctx context.Context, arg InsertChunkParams) (Chunk, error)
	InsertEpisode(ctx context.Context, arg InsertEpisodeParams) (Episode, error)
	// Starter query set for W12-02 (HANDOFF S4: Go + sqlc-generated queries).
	// Later tasks add more queries to this file as they need them; sqlc
	// regenerates the whole package from the union of every *.sql file here.
	InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error)
	InsertTask(ctx context.Context, arg InsertTaskParams) (Task, error)
	ListEventsByTrace(ctx context.Context, traceID string) ([]Event, error)
	UpdateTaskState(ctx context.Context, arg UpdateTaskStateParams) error
}

var _ Querier = (*Queries)(nil)
