// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"
	"database/sql"
)

type Querier interface {
	// Called ONLY from inside InsertEventWithDigest's own transaction,
	// immediately after that same transaction's InsertEvent - both writes
	// commit or roll back together, so the digest can never fall out of sync
	// with the ledger it claims to cover (task spec's own "never an event
	// without its digest step, never a digest step without its event").
	AdvanceLedgerDigestState(ctx context.Context, arg AdvanceLedgerDigestStateParams) error
	// The atomic single-claim guarantee (mirrors ConsumeApprovalToken/
	// ConsumePendingApproval's own "UPDATE ... WHERE <still claimable>"
	// pattern elsewhere in this file): only the FIRST dispatcher to run this
	// UPDATE against a given row - while its lease is still unheld or already
	// expired - ever affects a row; a losing concurrent dispatcher's identical
	// call affects 0 rows and must not touch that row at all. attempts is
	// incremented on every successful claim (task spec step 7: "attempts
	// increments on each claim"), including a crash-safe re-claim after a
	// previous lease expired without the row ever being acknowledged.
	ClaimOutboxRow(ctx context.Context, arg ClaimOutboxRowParams) (int64, error)
	// The single atomic single-use guarantee (HANDOFF S5 safety #5): only the
	// FIRST caller to run this UPDATE against a given token_hash ever affects
	// a row (consumed_at IS NULL is only ever true once); every later call
	// against the same token_hash - correct bytes or not - affects 0 rows and
	// kahyad/internal/policy/tokens.go treats that as a replay/unknown-token
	// failure. Bytes-hash/expiry comparison happens in Go, in a follow-up
	// GetApprovalToken call, AFTER this UPDATE has already burned the token -
	// so even a wrong-hash first presentation consumes it (no multi-guess
	// window against a live token).
	ConsumeApprovalToken(ctx context.Context, arg ConsumeApprovalTokenParams) (int64, error)
	// The single atomic single-use guarantee (the same "UPDATE ... WHERE x IS
	// NULL" pattern ConsumeApprovalToken above already uses for one-time
	// approval tokens): only the FIRST Engine.Approve/Deny call against a
	// given pending_approval_id ever affects a row; a second call against the
	// same id - Approve or Deny, forged or genuine - affects 0 rows, which
	// kahyad/internal/policy/engine.go treats as already-used/rejects, minting
	// no token and performing no bookkeeping a second time.
	ConsumePendingApproval(ctx context.Context, arg ConsumePendingApprovalParams) (int64, error)
	// W5-01's once-per-day idempotency check: counts events of kind on the
	// UTC calendar date dateStr ("YYYY-MM-DD" - SQLite's date() truncates
	// created_at to exactly this, and every created_at this codebase writes
	// is already UTC RFC3339/RFC3339Nano, so no timezone conversion is
	// needed). kahyad/internal/briefing.Orchestrator.Run consults this
	// BEFORE ever classifying a single collector item or spawning a worker
	// for a scheduled OR manual run: a non-zero count for kind=
	// "briefing.delivered" means today's briefing already went out, so this
	// run logs briefing.skipped_duplicate and sends nothing - a missed-run-
	// fired-on-wake plus the regular 08:30 run can therefore never deliver
	// two notifications the same date.
	CountEventsByKindAndDate(ctx context.Context, arg CountEventsByKindAndDateParams) (int64, error)
	// The per-(task_id, tool_name, args_hash) attempt count the resume scan
	// compares against task.retry.w1_max_auto (task spec step 6: "at most
	// w1_max_auto auto-retries per (task_id, tool_name, args_hash)") - counts
	// every row ever inserted for this exact triple (every seq), regardless
	// of its current status.
	CountToolCallAttempts(ctx context.Context, arg CountToolCallAttemptsParams) (int64, error)
	DeleteChunksByEpisode(ctx context.Context, episodeID int64) error
	GetApprovalToken(ctx context.Context, tokenHash string) (ApprovalToken, error)
	// W3-02 (autonomy ladder engine) queries below: autonomy_state,
	// approval_tokens, undo_windows. See migrations/0003_autonomy_policy.sql
	// for the schema and kahyad/internal/policy/engine.go + tokens.go for the
	// only two callers.
	GetAutonomyState(ctx context.Context, arg GetAutonomyStateParams) (AutonomyState, error)
	// W3-05 (egress proxy) queries below: egress_budget persists each host's
	// daily byte counter across restarts. See
	// migrations/0004_egress_budget.sql for the schema and
	// kahyad/internal/egress/budget.go for the only caller.
	GetEgressBudget(ctx context.Context, arg GetEgressBudgetParams) (EgressBudget, error)
	GetEpisodeByPath(ctx context.Context, sourcePath sql.NullString) (GetEpisodeByPathRow, error)
	// W12-04 (corpus indexer) queries below. GetEpisodeByPath above does not
	// filter by source, which is fine for callers that only ever use one
	// source, but the indexer must scope its hash-compare lookup to
	// source='memory_file' specifically (task spec step 3), so it gets its own
	// query rather than overloading GetEpisodeByPath's signature.
	GetEpisodeBySourceAndPath(ctx context.Context, arg GetEpisodeBySourceAndPathParams) (GetEpisodeBySourceAndPathRow, error)
	// The most recent anchor_log row of ANY status - push.go's
	// claimPendingRow uses this to decide whether there is already an
	// in-flight 'pending' row to retry (offline case, task spec step 5) before
	// ever considering a new one.
	GetLatestAnchorLog(ctx context.Context) (AnchorLog, error)
	// W4-05 (ledger external anchor + tamper detection) queries below. See
	// migrations/0010_ledger_anchor.sql for the schema.
	//
	// ledger_digest_state queries: kahyad/internal/store.InsertEventWithDigest
	// (the ONE choke point that appends a row to events - see its own doc
	// comment for why it is the only caller of GetLedgerDigestState/
	// AdvanceLedgerDigestState) is the only writer; kahyad/internal/anchor's
	// push.go (to learn what to anchor next) and verify.go (as a bonus
	// cross-check against its own from-genesis recompute) are read-only
	// callers.
	GetLedgerDigestState(ctx context.Context) (LedgerDigestState, error)
	// Idempotent-open lookup (post-security-review amendment): Engine.Check's
	// W1 auto-allow path (and Approve's W1 bookkeeping) call this FIRST and
	// reuse an already-OPEN window for the same (task_id, tool, trace_id)
	// instead of opening a second one on a retried call - a retry must never
	// leave multiple simultaneously-open undo windows for the same action.
	GetOpenUndoWindowByTaskToolTrace(ctx context.Context, arg GetOpenUndoWindowByTaskToolTraceParams) (UndoWindow, error)
	// Sessions/tasks are not guaranteed to open exactly one undo window per
	// trace_id, so this returns the most recently opened OPEN one - the same
	// "most recent wins" convention GetTaskBySession above already uses.
	GetOpenUndoWindowByTrace(ctx context.Context, traceID string) (UndoWindow, error)
	GetPendingApproval(ctx context.Context, id string) (PendingApproval, error)
	// The idempotent-replay lookup (task spec step 4): the most recent
	// status='receipt' row for this exact (task_id, tool_name, args_hash)
	// triple, if any. A hit means "do not re-execute - return this stored
	// receipt_json instead" (kahyad/internal/task.Receipts.Execute), which is
	// the mechanism that makes resume double-execution-safe.
	GetReceiptToolCall(ctx context.Context, arg GetReceiptToolCallParams) (ToolCall, error)
	// W4-03 (taint tiers + Reader/Actor split) queries below. See
	// migrations/0009_session_taint.sql for the schema and
	// kahyad/internal/taint/taint.go for the only caller (a narrow Store
	// interface there - never sqlcgen directly - so kahyad/internal/policy's
	// taint-check hook and kahyad/internal/reader's actor-seeding path both
	// depend on that package's own contract, not on sqlc's generated shapes).
	GetSessionTaint(ctx context.Context, sessionID string) (SessionTaint, error)
	// W4-02 (task durability state machine + receipts + outbox redelivery)
	// queries below. See migrations/0007_task_durability.sql for the schema;
	// kahyad/internal/task (machine.go/receipts.go/resume.go) and
	// kahyad/internal/outbox (dispatcher.go) are the only callers.
	// Column list matches tasks' own physical column order exactly, so sqlc
	// reuses the existing Task model type here rather than emitting a second,
	// differently-ordered Row type (the same convention InsertTask's own doc
	// comment already established for lane/secret_category).
	GetTaskByID(ctx context.Context, id string) (Task, error)
	// Sessions are not currently guaranteed to map to exactly one task row
	// (resume/retry may append more), so this returns the most recently
	// updated task for the session.
	GetTaskBySession(ctx context.Context, sessionID sql.NullString) (GetTaskBySessionRow, error)
	GetTaskLane(ctx context.Context, id string) (GetTaskLaneRow, error)
	// W4-03 BLOCKER 1+2 fix: the by-trace_id half of the server-side taint
	// resolver (kahyad/internal/policy.StoreSessionResolver) - a policy
	// decision must resolve WHICH session a request belongs to from the
	// request's own trace_id/task_id correlation, never from a caller-
	// supplied session_id (untrusted; on POST /v1/mcp there is no session_id
	// on the wire at all - see mcp.go's policyGateMiddleware). Mirrors
	// GetTaskBySession's own "not guaranteed unique, most-recently-updated
	// wins" note: a resumed/retried task can share one trace_id across more
	// than one tasks row. NULL session_id (no session_started yet for this
	// task) comes back as a NULL/invalid value, not an error - the resolver
	// itself treats that as "unresolved" (fail-closed), not a query failure.
	GetTaskSessionByTrace(ctx context.Context, traceID string) (sql.NullString, error)
	// Update-half of an application-level upsert (the same "upsert (update
	// half) then fall back to Insert on 0 rows" pattern UpdateAutonomyState/
	// UpdateEpisodeContent above already use in this file) - the common case
	// once a (host, day) row already exists.
	IncrementEgressBudget(ctx context.Context, arg IncrementEgressBudgetParams) (int64, error)
	// Bumps tasks.attempts by one and returns the new value - used both by
	// Machine.Transition (every fresh dispatch INTO 'executing') and by the
	// resume scan's within-cap W1 receipt-less retry path (which re-dispatches
	// without any status change, since the task never leaves 'executing').
	IncrementTaskAttempts(ctx context.Context, arg IncrementTaskAttemptsParams) (int64, error)
	// anchor_log queries: kahyad/internal/anchor/push.go is the only writer
	// (InsertAnchorLog/MarkAnchorPushed); push.go and verify.go both read.
	// status is always 'pending' at insert time (task spec step 3: "insert
	// anchor_log row pending" BEFORE the git push is even attempted) - the
	// caller passes the literal string, never a variable, so this file has
	// exactly one place that ever creates a 'pending' row.
	InsertAnchorLog(ctx context.Context, arg InsertAnchorLogParams) (AnchorLog, error)
	// consumed_at starts NULL (a literal, not a param - see
	// ConsumeApprovalToken below for the only statement that ever sets it).
	// class/scope persist the token's REAL bound identity (post-security-
	// review amendment) so a consume-failure demotion can target this exact
	// triple, recovered by token_hash - never whatever (tool,class,scope) the
	// /policy/consume-token caller happens to claim.
	InsertApprovalToken(ctx context.Context, arg InsertApprovalTokenParams) error
	InsertAutonomyState(ctx context.Context, arg InsertAutonomyStateParams) error
	InsertChunk(ctx context.Context, arg InsertChunkParams) (Chunk, error)
	InsertEgressBudget(ctx context.Context, arg InsertEgressBudgetParams) error
	InsertEpisode(ctx context.Context, arg InsertEpisodeParams) (InsertEpisodeRow, error)
	// Starter query set for W12-02 (HANDOFF S4: Go + sqlc-generated queries).
	// Later tasks add more queries to this file as they need them; sqlc
	// regenerates the whole package from the union of every *.sql file here.
	InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error)
	// One hot-window candidate fact: source_tier is ALWAYS 'agent_derived'
	// here (quarantined from profile-card/injection until a human confirms -
	// kahyad/internal/server's own quarantinedSourceTier), evidentiality is
	// 'inferred' (the extractor read the raw chunk text, it did not witness
	// or get told the fact directly), confidence is a caller-supplied
	// log-odds value (this column is LOG-ODDS, never a bare probability -
	// 0001_init_schema.sql's own header note), evidence cites the raw
	// episode/chunk this fact was promoted from (e.g. "episode:12,chunk:34"),
	// never a prior summary.
	InsertFact(ctx context.Context, arg InsertFactParams) (Fact, error)
	// W4-02 outbox lease/redelivery queries. See migrations/
	// 0007_task_durability.sql for the added columns and
	// kahyad/internal/outbox/dispatcher.go for the only caller.
	// available_at defaults to "now" (immediately dispatchable); lease_until
	// starts NULL (never claimed) and attempts starts 0 - both only ever
	// change via ClaimOutboxRow below.
	InsertOutboxRow(ctx context.Context, arg InsertOutboxRowParams) (Outbox, error)
	// Post-security-review amendment: pending_approvals queries below back the
	// server-issued, single-use pending_approval_id (see
	// migrations/0003_autonomy_policy.sql's doc comment - a NEEDS_APPROVAL
	// decision used to hand back an unsigned, caller-decodable blob; it is now
	// an opaque random id bound to a DB row only kahyad/internal/policy/
	// engine.go writes/reads).
	// consumed_at starts NULL (a literal, not a param - see
	// ConsumePendingApproval below for the only statement that ever sets it).
	// tool_input (W3-06) persists the EXACT bytes Engine.Check received, so
	// `kahya approvals`/`kahya approve <id>` can render a real WYSIWYE diff,
	// not just prove after the fact (via approved_bytes_hash) that nothing
	// changed. Listed last (matching the column's physical ALTER-TABLE-added
	// position - see 0005_pending_approval_payload.sql) so GetPendingApproval/
	// ListUnconsumedPendingApprovals below reuse the PendingApproval model
	// type directly instead of sqlc emitting a separate "Row" type for a
	// differently-ordered column list.
	InsertPendingApproval(ctx context.Context, arg InsertPendingApprovalParams) error
	// The ONLY way a 'clean' row is ever created (task spec step 1): a plain
	// INSERT, never an upsert - a session_id that already has ANY row (clean
	// or tainted) makes this fail on the PRIMARY KEY constraint, which
	// kahyad/internal/taint.Tracker.InsertClean treats as a "lowering
	// attempt" (ledgered taint.lower_attempt, rejected) rather than silently
	// overwriting an existing row. reason is always NULL for a clean insert -
	// there is nothing to explain about a session starting clean, unlike
	// RaiseSessionTaint below.
	InsertSessionTaintClean(ctx context.Context, arg InsertSessionTaintCleanParams) error
	// W5-01's THIRD birth-place for a session_taint row (kahyad/internal/
	// taint's own package doc comment names exactly two before this: the
	// OnSession InsertClean for a user-initiated task, and actor_seed.Spawn's
	// InsertClean for a freshly-seeded Actor). This one is for a session that
	// is UNTRUSTED BY DESIGN AT CREATION (the morning-briefing worker session
	// - HANDOFF S5 safety #2: the briefing is untrusted by design)
	// - never a session that started clean and later had content-sourced
	// taint Raised onto it. A plain INSERT, mirroring InsertSessionTaintClean
	// exactly except for the literal tier: a session_id that already has ANY
	// row makes this fail on the PRIMARY KEY constraint -
	// kahyad/internal/taint.Tracker.InsertUntrusted surfaces that as an error
	// (a caller minting a brand-new session_id that collides with an existing
	// row has a bug worth surfacing), rather than silently reusing
	// RaiseSessionTaint's upsert semantics.
	InsertSessionTaintTainted(ctx context.Context, arg InsertSessionTaintTaintedParams) error
	// lane/secret_category (W3-08): the caller ALREADY knows this task's
	// secret-lane verdict before this row is ever created (kahyad/internal/
	// server's POST /v1/task handler runs kahyad/internal/secretlane's
	// classifier BEFORE calling InsertTask - the ordering invariant, HANDOFF
	// S4 flag - so there is no window where a task row exists with an
	// unclassified lane). The RETURNING clause lists every physical column
	// (including status/next_retry_at/attempts, W4-02's 0007_task_durability
	// ALTER TABLEs - left OUT of the INSERT column/VALUES list itself, so
	// every existing caller keeps inserting a row that takes their DEFAULTs
	// unchanged: status='intent', attempts=0, next_retry_at=NULL) so sqlc
	// reuses the existing Task model type here rather than generating a
	// second, differently-ordered InsertTaskRow type.
	InsertTask(ctx context.Context, arg InsertTaskParams) (Task, error)
	// Step 1 of the intent -> executing -> {receipt, failed} lifecycle
	// (kahyad/internal/task.Receipts.Execute): one row per side-effectful
	// (W1/W2/W3) tool-call ATTEMPT - seq lets the SAME (task_id, tool_name,
	// args_hash) triple be re-attempted (a fresh row at a higher seq) after an
	// earlier attempt at that exact triple was marked 'failed' by the resume
	// scan, while the idempotent-replay lookup (GetReceiptToolCall below)
	// only ever matches an attempt that reached 'receipt'.
	InsertToolCallIntent(ctx context.Context, arg InsertToolCallIntentParams) (ToolCall, error)
	InsertUndoWindow(ctx context.Context, arg InsertUndoWindowParams) (UndoWindow, error)
	ListActiveMemoryFileEpisodes(ctx context.Context) ([]ListActiveMemoryFileEpisodesRow, error)
	// Every ledger event ever appended, oldest first - verify.go's own
	// full-recompute pass (task spec step 6: "recompute the digest from event
	// 1 upward"; "Full recompute is fine at MVP scale ... do not optimize").
	ListAllEvents(ctx context.Context) ([]Event, error)
	// Every anchor_log row ordered by the ledger position it anchors -
	// verify.go's own recompute-from-event-1 pass uses this as its ordered
	// checkpoint list (task spec step 6: "at each anchor_log/remote anchor
	// line, compare").
	ListAnchorLogs(ctx context.Context) ([]AnchorLog, error)
	ListAutonomyState(ctx context.Context) ([]AutonomyState, error)
	ListChunkIDsByEpisode(ctx context.Context, episodeID int64) ([]int64, error)
	// W5-02 (nightly consolidation) queries below: hot-window detail-atom
	// promotion (facts INSERT, episodes.cooled_at) - see
	// kahyad/internal/consolidation/hotwindow.go.
	// Raw chunk text for one episode, in sequence order - hotwindow.go scans
	// this text for detail atoms (numbers/dates/quotes/decisions/promises).
	// Every fact promoted from it cites these chunk ids as evidence, never a
	// prior summary (HANDOFF S5 memory #4: "her ozet ham kanittan uretilir,
	// asla alt-ozetten").
	ListChunksByEpisode(ctx context.Context, episodeID int64) ([]Chunk, error)
	// Candidate rows for one dispatcher claim pass: not yet delivered,
	// available (available_at <= now), and not currently leased by another
	// dispatcher (lease_until IS NULL, i.e. never claimed, OR lease_until has
	// already passed, i.e. a previous claim's lease expired without being
	// acknowledged - the crash-safe re-claim path). Listing candidates and
	// claiming them are two separate steps ON PURPOSE (ClaimOutboxRow below)
	// so two concurrent dispatchers racing on the SAME candidate list each
	// only ever win the atomic UPDATE for rows the other hasn't already
	// claimed first.
	ListDueOutboxRows(ctx context.Context, arg ListDueOutboxRowsParams) ([]Outbox, error)
	// W12-08 (anthproxy cost governor): boot-time rebuild reads every
	// historical event of one kind (e.g. 'model_call') and replays it into
	// the in-memory governor totals - kahyad/internal/anthproxy stays
	// store-agnostic (it never imports this package); main.go converts each
	// row into an anthproxy.BootEvent.
	ListEventsByKind(ctx context.Context, kind string) ([]Event, error)
	ListEventsByTrace(ctx context.Context, traceID string) ([]Event, error)
	// The resume scan's candidate set (kahyad startup + periodic tick):
	// every task currently recorded as 'executing'. kahyad/internal/task's
	// own LiveRegistry then filters this down to the ones with NO live worker
	// PID - a live task is simply skipped (the daemon itself is still running
	// it).
	ListExecutingTasks(ctx context.Context) ([]Task, error)
	ListOpenUndoWindows(ctx context.Context) ([]UndoWindow, error)
	// Every not-yet-pushed anchor_log row, oldest first - push.go's
	// stale-pending alarm (task spec step 5: "if the oldest pending is older
	// than 2 x interval_hours, alarm") reads index [0].
	ListPendingAnchorLogs(ctx context.Context) ([]AnchorLog, error)
	// Every tool_calls row for task_id still stuck at 'intent'/'executing' -
	// i.e. a side-effectful call whose kahyad-side execution was interrupted
	// (worker died, kahyad crashed) before a receipt (or a failure) was ever
	// recorded. Ordered most-recent-first: the resume scan (task spec step 6)
	// only ever needs the single most recent one - realistically there is at
	// most one such row per task at any moment, but the scan itself is
	// defensive about that.
	ListReceiptlessToolCalls(ctx context.Context, taskID string) ([]ToolCall, error)
	// `kahya task show <id>`'s tool_calls listing, oldest attempt first.
	ListToolCallsByTask(ctx context.Context, taskID string) ([]ToolCall, error)
	// W3-06 `kahya approvals`: every not-yet-consumed row, oldest first.
	// Expiry is checked in Go (kahyad/internal/policy.Engine.ListPendingApprovals),
	// mirroring getValidPendingApproval's own time.Parse+time.After check,
	// rather than comparing RFC3339Nano strings in SQL (that format's
	// trailing-zero-trimmed fractional seconds do NOT always sort
	// lexicographically in timestamp order).
	ListUnconsumedPendingApprovals(ctx context.Context) ([]PendingApproval, error)
	// Active episodes not yet hot-window-cooled, created at or before cutoff
	// (RFC3339 UTC string compare - every created_at this codebase writes is
	// already normalized to that format, so a plain string comparison sorts
	// correctly, matching CountEventsByKindAndDate's own date()-free
	// convention above for the same reason).
	ListUncooledEpisodesOlderThan(ctx context.Context, createdAt string) ([]ListUncooledEpisodesOlderThanRow, error)
	// The ONLY statement that ever flips a row from 'pending' to 'pushed' -
	// called once the git push has actually landed on the remote (task spec
	// step 3: "On success mark pushed").
	MarkAnchorPushed(ctx context.Context, arg MarkAnchorPushedParams) error
	// Stamped ONLY after this episode's detail atoms have been promoted to
	// facts (task spec step 6: "only then mark cooled").
	MarkEpisodeCooled(ctx context.Context, arg MarkEpisodeCooledParams) error
	MarkEpisodeDeleted(ctx context.Context, id int64) error
	// Terminal success: the re-spawned worker exited 0 (task spec step 7).
	MarkOutboxDelivered(ctx context.Context, arg MarkOutboxDeliveredParams) error
	MarkToolCallExecuting(ctx context.Context, arg MarkToolCallExecutingParams) error
	// Used both when a tool's own effect function returns an error (genuine
	// execution failure) AND by the resume scan, which marks a receipt-less
	// 'intent'/'executing' row 'failed' before deciding whether to auto-retry
	// (W1, within cap) or escalate to blocked_user (W1 past cap, or any
	// W2/W3).
	MarkToolCallFailed(ctx context.Context, arg MarkToolCallFailedParams) error
	// The terminal success state: receipt_json (result + result hash) is
	// written in the SAME database transaction that commits the tool's own
	// DB-side effects, immediately once the side effect completes (task spec
	// step 3) - kahyad/internal/task.Receipts.Execute runs this inside the
	// same *sql.Tx as the caller-supplied effect function whenever that
	// effect writes to brain.db itself.
	MarkToolCallReceipt(ctx context.Context, arg MarkToolCallReceiptParams) error
	// The next seq value for a (task_id, tool_name, args_hash) triple (1 for a
	// never-attempted triple).
	NextToolCallSeq(ctx context.Context, arg NextToolCallSeqParams) (int64, error)
	// The ONLY tier-transition statement in this file: upserts session_id to
	// tier='tainted', creating the row if it did not exist yet (a
	// content-sourced tool output can raise taint on a session before that
	// session's OWN 'clean' row ever landed - the ordering invariant is "no
	// byte reaches the worker before this Raise call", not "the row must
	// already exist") or flipping an existing 'clean' row to 'tainted' (and
	// leaving an already-'tainted' row at 'tainted', updating reason/
	// updated_at regardless - taint only ever rises, so re-raising a
	// different reason is fine, re-raising the SAME tier is a no-op by
	// definition). There is no corresponding statement anywhere in this
	// codebase that ever sets tier back to 'clean' on an existing row.
	RaiseSessionTaint(ctx context.Context, arg RaiseSessionTaintParams) error
	// Task durability BLOCKER 2(b) fix: kahyad/internal/outbox.Dispatcher's
	// heartbeat goroutine calls this every leaseDuration/3 for as long as
	// spawn.Run blocks on a claimed row's re-spawned worker, so a
	// longer-than-one-lease-period task is never re-claimed by a second
	// dispatcher pass purely because its ORIGINAL lease (computed once at
	// claim time) elapsed while the worker was still genuinely running.
	// Scoped to dispatched_at IS NULL defensively - a row this dispatcher has
	// already marked delivered (or that somehow no longer exists) must never
	// have its lease resurrected.
	RenewOutboxLease(ctx context.Context, arg RenewOutboxLeaseParams) error
	// W3-08 (secret-lane routing) queries below: lane/secret_category are
	// STICKY (kahyad/internal/secretlane.Escalate enforces "only ever widens,
	// never downgrades" in Go, not SQL - see 0006_secret_lane.sql's own doc
	// comment). kahyad/internal/secretlane.NewProxyBackstopHook (the W12-08
	// proxy chokepoint) is GetTaskLane's other caller, consulted on EVERY
	// forwarded model-call request.
	SetTaskLane(ctx context.Context, arg SetTaskLaneParams) error
	// W4-04: writes tasks.next_retry_at when kahyad/internal/task.CloudRetry
	// parks a task in 'bekliyor-yeniden-deneme' (the status change itself
	// goes through Machine.Transition/SetTaskStatus, same as every other
	// transition - this query ONLY ever touches next_retry_at, so a caller
	// always calls both, never this alone).
	SetTaskNextRetry(ctx context.Context, arg SetTaskNextRetryParams) error
	// The ONLY writer of tasks.status is kahyad/internal/task.Machine.Transition
	// - every status change is preceded by that function's own legal-transition
	// check and followed by a task.transition (or task.illegal_transition)
	// ledger event; this query performs no validation of its own.
	//
	// task durability BLOCKER 3 fix: the WHERE clause's own "status = ?" (the
	// FROM status Machine.Transition just read via GetTaskByID) makes this an
	// atomic compare-and-set, not a blind write - two concurrent Transition
	// calls racing from the SAME stale 'from' read can now only ever have ONE
	// of them actually affect a row (rows-affected 1); the loser affects 0
	// rows (its 'from' no longer matches - some other transition already won)
	// and Machine.Transition treats that as a lost race, never silently
	// overwriting whatever the winner just wrote (no more last-write-wins).
	SetTaskStatus(ctx context.Context, arg SetTaskStatusParams) (int64, error)
	SetUndoWindowState(ctx context.Context, arg SetUndoWindowStateParams) error
	// Update-half of an application-level upsert (kahyad/internal/policy
	// calls this first; a 0-rows-affected result means no row exists yet, so
	// it falls back to InsertAutonomyState - the same "upsert (update half)"
	// pattern UpdateEpisodeContent above already uses in this file).
	UpdateAutonomyState(ctx context.Context, arg UpdateAutonomyStateParams) (int64, error)
	// Upserts (update half) an existing memory_file episode in place on
	// new/changed content: same id, fresh hash/tier, status forced back to
	// 'active' (covers the resurrect-a-deleted-file case, not just plain edits).
	UpdateEpisodeContent(ctx context.Context, arg UpdateEpisodeContentParams) error
	// Persists a worker-reported session_id onto the task row (W12-07 step 3:
	// kahyad "persists session_id onto the task row" as the worker's
	// {"type":"session",...} stdout line arrives). Session RESUME itself
	// (using a stored session_id to continue a LATER task) is W4-02; this
	// query only records the value as it arrives.
	UpdateTaskSession(ctx context.Context, arg UpdateTaskSessionParams) error
	UpdateTaskState(ctx context.Context, arg UpdateTaskStateParams) error
}

var _ Querier = (*Queries)(nil)
