// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const claimOutboxRow = `-- name: ClaimOutboxRow :execrows
UPDATE outbox
SET lease_until = ?, attempts = attempts + 1
WHERE id = ? AND dispatched_at IS NULL AND (lease_until IS NULL OR lease_until < ?)
`

type ClaimOutboxRowParams struct {
	LeaseUntil   sql.NullString `json:"lease_until"`
	ID           int64          `json:"id"`
	LeaseUntil_2 sql.NullString `json:"lease_until_2"`
}

// The atomic single-claim guarantee (mirrors ConsumeApprovalToken/
// ConsumePendingApproval's own "UPDATE ... WHERE <still claimable>"
// pattern elsewhere in this file): only the FIRST dispatcher to run this
// UPDATE against a given row - while its lease is still unheld or already
// expired - ever affects a row; a losing concurrent dispatcher's identical
// call affects 0 rows and must not touch that row at all. attempts is
// incremented on every successful claim (task spec step 7: "attempts
// increments on each claim"), including a crash-safe re-claim after a
// previous lease expired without the row ever being acknowledged.
func (q *Queries) ClaimOutboxRow(ctx context.Context, arg ClaimOutboxRowParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimOutboxRow, arg.LeaseUntil, arg.ID, arg.LeaseUntil_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const consumeApprovalToken = `-- name: ConsumeApprovalToken :execrows
UPDATE approval_tokens
SET consumed_at = ?
WHERE token_hash = ? AND consumed_at IS NULL
`

type ConsumeApprovalTokenParams struct {
	ConsumedAt sql.NullString `json:"consumed_at"`
	TokenHash  string         `json:"token_hash"`
}

// The single atomic single-use guarantee (HANDOFF S5 safety #5): only the
// FIRST caller to run this UPDATE against a given token_hash ever affects
// a row (consumed_at IS NULL is only ever true once); every later call
// against the same token_hash - correct bytes or not - affects 0 rows and
// kahyad/internal/policy/tokens.go treats that as a replay/unknown-token
// failure. Bytes-hash/expiry comparison happens in Go, in a follow-up
// GetApprovalToken call, AFTER this UPDATE has already burned the token -
// so even a wrong-hash first presentation consumes it (no multi-guess
// window against a live token).
func (q *Queries) ConsumeApprovalToken(ctx context.Context, arg ConsumeApprovalTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeApprovalToken, arg.ConsumedAt, arg.TokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const consumePendingApproval = `-- name: ConsumePendingApproval :execrows
UPDATE pending_approvals
SET consumed_at = ?
WHERE id = ? AND consumed_at IS NULL
`

type ConsumePendingApprovalParams struct {
	ConsumedAt sql.NullString `json:"consumed_at"`
	ID         string         `json:"id"`
}

// The single atomic single-use guarantee (the same "UPDATE ... WHERE x IS
// NULL" pattern ConsumeApprovalToken above already uses for one-time
// approval tokens): only the FIRST Engine.Approve/Deny call against a
// given pending_approval_id ever affects a row; a second call against the
// same id - Approve or Deny, forged or genuine - affects 0 rows, which
// kahyad/internal/policy/engine.go treats as already-used/rejects, minting
// no token and performing no bookkeeping a second time.
func (q *Queries) ConsumePendingApproval(ctx context.Context, arg ConsumePendingApprovalParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumePendingApproval, arg.ConsumedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countToolCallAttempts = `-- name: CountToolCallAttempts :one
SELECT COUNT(*) FROM tool_calls WHERE task_id = ? AND tool_name = ? AND args_hash = ?
`

type CountToolCallAttemptsParams struct {
	TaskID   string `json:"task_id"`
	ToolName string `json:"tool_name"`
	ArgsHash string `json:"args_hash"`
}

// The per-(task_id, tool_name, args_hash) attempt count the resume scan
// compares against task.retry.w1_max_auto (task spec step 6: "at most
// w1_max_auto auto-retries per (task_id, tool_name, args_hash)") - counts
// every row ever inserted for this exact triple (every seq), regardless
// of its current status.
func (q *Queries) CountToolCallAttempts(ctx context.Context, arg CountToolCallAttemptsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countToolCallAttempts, arg.TaskID, arg.ToolName, arg.ArgsHash)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteChunksByEpisode = `-- name: DeleteChunksByEpisode :exec
DELETE FROM chunks WHERE episode_id = ?
`

func (q *Queries) DeleteChunksByEpisode(ctx context.Context, episodeID int64) error {
	_, err := q.db.ExecContext(ctx, deleteChunksByEpisode, episodeID)
	return err
}

const getApprovalToken = `-- name: GetApprovalToken :one
SELECT token_hash, task_id, trace_id, tool, class, scope, approved_bytes_hash, minted_at, expires_at, consumed_at
FROM approval_tokens
WHERE token_hash = ?
`

func (q *Queries) GetApprovalToken(ctx context.Context, tokenHash string) (ApprovalToken, error) {
	row := q.db.QueryRowContext(ctx, getApprovalToken, tokenHash)
	var i ApprovalToken
	err := row.Scan(
		&i.TokenHash,
		&i.TaskID,
		&i.TraceID,
		&i.Tool,
		&i.Class,
		&i.Scope,
		&i.ApprovedBytesHash,
		&i.MintedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const getAutonomyState = `-- name: GetAutonomyState :one

SELECT tool, class, scope, level, consecutive_approvals, updated_at
FROM autonomy_state
WHERE tool = ? AND class = ? AND scope = ?
`

type GetAutonomyStateParams struct {
	Tool  string `json:"tool"`
	Class string `json:"class"`
	Scope string `json:"scope"`
}

// W3-02 (autonomy ladder engine) queries below: autonomy_state,
// approval_tokens, undo_windows. See migrations/0003_autonomy_policy.sql
// for the schema and kahyad/internal/policy/engine.go + tokens.go for the
// only two callers.
func (q *Queries) GetAutonomyState(ctx context.Context, arg GetAutonomyStateParams) (AutonomyState, error) {
	row := q.db.QueryRowContext(ctx, getAutonomyState, arg.Tool, arg.Class, arg.Scope)
	var i AutonomyState
	err := row.Scan(
		&i.Tool,
		&i.Class,
		&i.Scope,
		&i.Level,
		&i.ConsecutiveApprovals,
		&i.UpdatedAt,
	)
	return i, err
}

const getEgressBudget = `-- name: GetEgressBudget :one

SELECT host, day, bytes FROM egress_budget WHERE host = ? AND day = ?
`

type GetEgressBudgetParams struct {
	Host string `json:"host"`
	Day  string `json:"day"`
}

// W3-05 (egress proxy) queries below: egress_budget persists each host's
// daily byte counter across restarts. See
// migrations/0004_egress_budget.sql for the schema and
// kahyad/internal/egress/budget.go for the only caller.
func (q *Queries) GetEgressBudget(ctx context.Context, arg GetEgressBudgetParams) (EgressBudget, error) {
	row := q.db.QueryRowContext(ctx, getEgressBudget, arg.Host, arg.Day)
	var i EgressBudget
	err := row.Scan(&i.Host, &i.Day, &i.Bytes)
	return i, err
}

const getEpisodeByPath = `-- name: GetEpisodeByPath :one
SELECT id, source, source_path, source_hash, source_tier, started_at, ended_at, status, meta, created_at
FROM episodes
WHERE source_path = ?
LIMIT 1
`

func (q *Queries) GetEpisodeByPath(ctx context.Context, sourcePath sql.NullString) (Episode, error) {
	row := q.db.QueryRowContext(ctx, getEpisodeByPath, sourcePath)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.SourcePath,
		&i.SourceHash,
		&i.SourceTier,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
		&i.Meta,
		&i.CreatedAt,
	)
	return i, err
}

const getEpisodeBySourceAndPath = `-- name: GetEpisodeBySourceAndPath :one

SELECT id, source, source_path, source_hash, source_tier, started_at, ended_at, status, meta, created_at
FROM episodes
WHERE source = ? AND source_path = ?
LIMIT 1
`

type GetEpisodeBySourceAndPathParams struct {
	Source     string         `json:"source"`
	SourcePath sql.NullString `json:"source_path"`
}

// W12-04 (corpus indexer) queries below. GetEpisodeByPath above does not
// filter by source, which is fine for callers that only ever use one
// source, but the indexer must scope its hash-compare lookup to
// source='memory_file' specifically (task spec step 3), so it gets its own
// query rather than overloading GetEpisodeByPath's signature.
func (q *Queries) GetEpisodeBySourceAndPath(ctx context.Context, arg GetEpisodeBySourceAndPathParams) (Episode, error) {
	row := q.db.QueryRowContext(ctx, getEpisodeBySourceAndPath, arg.Source, arg.SourcePath)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.SourcePath,
		&i.SourceHash,
		&i.SourceTier,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
		&i.Meta,
		&i.CreatedAt,
	)
	return i, err
}

const getOpenUndoWindowByTaskToolTrace = `-- name: GetOpenUndoWindowByTaskToolTrace :one
SELECT id, task_id, tool, trace_id, opened_at, deadline, state
FROM undo_windows
WHERE task_id = ? AND tool = ? AND trace_id = ? AND state = 'open'
ORDER BY opened_at DESC
LIMIT 1
`

type GetOpenUndoWindowByTaskToolTraceParams struct {
	TaskID  string `json:"task_id"`
	Tool    string `json:"tool"`
	TraceID string `json:"trace_id"`
}

// Idempotent-open lookup (post-security-review amendment): Engine.Check's
// W1 auto-allow path (and Approve's W1 bookkeeping) call this FIRST and
// reuse an already-OPEN window for the same (task_id, tool, trace_id)
// instead of opening a second one on a retried call - a retry must never
// leave multiple simultaneously-open undo windows for the same action.
func (q *Queries) GetOpenUndoWindowByTaskToolTrace(ctx context.Context, arg GetOpenUndoWindowByTaskToolTraceParams) (UndoWindow, error) {
	row := q.db.QueryRowContext(ctx, getOpenUndoWindowByTaskToolTrace, arg.TaskID, arg.Tool, arg.TraceID)
	var i UndoWindow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Tool,
		&i.TraceID,
		&i.OpenedAt,
		&i.Deadline,
		&i.State,
	)
	return i, err
}

const getOpenUndoWindowByTrace = `-- name: GetOpenUndoWindowByTrace :one
SELECT id, task_id, tool, trace_id, opened_at, deadline, state
FROM undo_windows
WHERE trace_id = ? AND state = 'open'
ORDER BY opened_at DESC
LIMIT 1
`

// Sessions/tasks are not guaranteed to open exactly one undo window per
// trace_id, so this returns the most recently opened OPEN one - the same
// "most recent wins" convention GetTaskBySession above already uses.
func (q *Queries) GetOpenUndoWindowByTrace(ctx context.Context, traceID string) (UndoWindow, error) {
	row := q.db.QueryRowContext(ctx, getOpenUndoWindowByTrace, traceID)
	var i UndoWindow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Tool,
		&i.TraceID,
		&i.OpenedAt,
		&i.Deadline,
		&i.State,
	)
	return i, err
}

const getPendingApproval = `-- name: GetPendingApproval :one
SELECT id, task_id, trace_id, tool, class, scope, approved_bytes_hash, minted_at, expires_at, consumed_at, tool_input
FROM pending_approvals
WHERE id = ?
`

func (q *Queries) GetPendingApproval(ctx context.Context, id string) (PendingApproval, error) {
	row := q.db.QueryRowContext(ctx, getPendingApproval, id)
	var i PendingApproval
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.TraceID,
		&i.Tool,
		&i.Class,
		&i.Scope,
		&i.ApprovedBytesHash,
		&i.MintedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ToolInput,
	)
	return i, err
}

const getReceiptToolCall = `-- name: GetReceiptToolCall :one
SELECT id, task_id, seq, tool_name, class, args_hash, approval_token_id, status, receipt_json, started_at, finished_at, created_at
FROM tool_calls
WHERE task_id = ? AND tool_name = ? AND args_hash = ? AND status = 'receipt'
ORDER BY seq DESC
LIMIT 1
`

type GetReceiptToolCallParams struct {
	TaskID   string `json:"task_id"`
	ToolName string `json:"tool_name"`
	ArgsHash string `json:"args_hash"`
}

// The idempotent-replay lookup (task spec step 4): the most recent
// status='receipt' row for this exact (task_id, tool_name, args_hash)
// triple, if any. A hit means "do not re-execute - return this stored
// receipt_json instead" (kahyad/internal/task.Receipts.Execute), which is
// the mechanism that makes resume double-execution-safe.
func (q *Queries) GetReceiptToolCall(ctx context.Context, arg GetReceiptToolCallParams) (ToolCall, error) {
	row := q.db.QueryRowContext(ctx, getReceiptToolCall, arg.TaskID, arg.ToolName, arg.ArgsHash)
	var i ToolCall
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Seq,
		&i.ToolName,
		&i.Class,
		&i.ArgsHash,
		&i.ApprovalTokenID,
		&i.Status,
		&i.ReceiptJson,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionTaint = `-- name: GetSessionTaint :one

SELECT session_id, tier, reason, updated_at FROM session_taint WHERE session_id = ?
`

// W4-03 (taint tiers + Reader/Actor split) queries below. See
// migrations/0009_session_taint.sql for the schema and
// kahyad/internal/taint/taint.go for the only caller (a narrow Store
// interface there - never sqlcgen directly - so kahyad/internal/policy's
// taint-check hook and kahyad/internal/reader's actor-seeding path both
// depend on that package's own contract, not on sqlc's generated shapes).
func (q *Queries) GetSessionTaint(ctx context.Context, sessionID string) (SessionTaint, error) {
	row := q.db.QueryRowContext(ctx, getSessionTaint, sessionID)
	var i SessionTaint
	err := row.Scan(
		&i.SessionID,
		&i.Tier,
		&i.Reason,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one

SELECT id, trace_id, session_id, state, taint_tier, model, envelope, updated_at, created_at, lane, secret_category, status, next_retry_at, attempts
FROM tasks
WHERE id = ?
`

// W4-02 (task durability state machine + receipts + outbox redelivery)
// queries below. See migrations/0007_task_durability.sql for the schema;
// kahyad/internal/task (machine.go/receipts.go/resume.go) and
// kahyad/internal/outbox (dispatcher.go) are the only callers.
// Column list matches tasks' own physical column order exactly, so sqlc
// reuses the existing Task model type here rather than emitting a second,
// differently-ordered Row type (the same convention InsertTask's own doc
// comment already established for lane/secret_category).
func (q *Queries) GetTaskByID(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TraceID,
		&i.SessionID,
		&i.State,
		&i.TaintTier,
		&i.Model,
		&i.Envelope,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Lane,
		&i.SecretCategory,
		&i.Status,
		&i.NextRetryAt,
		&i.Attempts,
	)
	return i, err
}

const getTaskBySession = `-- name: GetTaskBySession :one
SELECT id, trace_id, session_id, state, taint_tier, model, envelope, updated_at, created_at
FROM tasks
WHERE session_id = ?
ORDER BY updated_at DESC
LIMIT 1
`

type GetTaskBySessionRow struct {
	ID        string         `json:"id"`
	TraceID   string         `json:"trace_id"`
	SessionID sql.NullString `json:"session_id"`
	State     string         `json:"state"`
	TaintTier string         `json:"taint_tier"`
	Model     sql.NullString `json:"model"`
	Envelope  sql.NullString `json:"envelope"`
	UpdatedAt string         `json:"updated_at"`
	CreatedAt string         `json:"created_at"`
}

// Sessions are not currently guaranteed to map to exactly one task row
// (resume/retry may append more), so this returns the most recently
// updated task for the session.
func (q *Queries) GetTaskBySession(ctx context.Context, sessionID sql.NullString) (GetTaskBySessionRow, error) {
	row := q.db.QueryRowContext(ctx, getTaskBySession, sessionID)
	var i GetTaskBySessionRow
	err := row.Scan(
		&i.ID,
		&i.TraceID,
		&i.SessionID,
		&i.State,
		&i.TaintTier,
		&i.Model,
		&i.Envelope,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTaskLane = `-- name: GetTaskLane :one
SELECT lane, secret_category FROM tasks WHERE id = ?
`

type GetTaskLaneRow struct {
	Lane           string         `json:"lane"`
	SecretCategory sql.NullString `json:"secret_category"`
}

func (q *Queries) GetTaskLane(ctx context.Context, id string) (GetTaskLaneRow, error) {
	row := q.db.QueryRowContext(ctx, getTaskLane, id)
	var i GetTaskLaneRow
	err := row.Scan(&i.Lane, &i.SecretCategory)
	return i, err
}

const getTaskSessionByTrace = `-- name: GetTaskSessionByTrace :one
SELECT session_id FROM tasks
WHERE trace_id = ?
ORDER BY updated_at DESC
LIMIT 1
`

// W4-03 BLOCKER 1+2 fix: the by-trace_id half of the server-side taint
// resolver (kahyad/internal/policy.StoreSessionResolver) - a policy
// decision must resolve WHICH session a request belongs to from the
// request's own trace_id/task_id correlation, never from a caller-
// supplied session_id (untrusted; on POST /v1/mcp there is no session_id
// on the wire at all - see mcp.go's policyGateMiddleware). Mirrors
// GetTaskBySession's own "not guaranteed unique, most-recently-updated
// wins" note: a resumed/retried task can share one trace_id across more
// than one tasks row. NULL session_id (no session_started yet for this
// task) comes back as a NULL/invalid value, not an error - the resolver
// itself treats that as "unresolved" (fail-closed), not a query failure.
func (q *Queries) GetTaskSessionByTrace(ctx context.Context, traceID string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getTaskSessionByTrace, traceID)
	var session_id sql.NullString
	err := row.Scan(&session_id)
	return session_id, err
}

const incrementEgressBudget = `-- name: IncrementEgressBudget :execrows
UPDATE egress_budget
SET bytes = bytes + ?
WHERE host = ? AND day = ?
`

type IncrementEgressBudgetParams struct {
	Bytes int64  `json:"bytes"`
	Host  string `json:"host"`
	Day   string `json:"day"`
}

// Update-half of an application-level upsert (the same "upsert (update
// half) then fall back to Insert on 0 rows" pattern UpdateAutonomyState/
// UpdateEpisodeContent above already use in this file) - the common case
// once a (host, day) row already exists.
func (q *Queries) IncrementEgressBudget(ctx context.Context, arg IncrementEgressBudgetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, incrementEgressBudget, arg.Bytes, arg.Host, arg.Day)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const incrementTaskAttempts = `-- name: IncrementTaskAttempts :one
UPDATE tasks
SET attempts = attempts + 1, updated_at = ?
WHERE id = ?
RETURNING attempts
`

type IncrementTaskAttemptsParams struct {
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

// Bumps tasks.attempts by one and returns the new value - used both by
// Machine.Transition (every fresh dispatch INTO 'executing') and by the
// resume scan's within-cap W1 receipt-less retry path (which re-dispatches
// without any status change, since the task never leaves 'executing').
func (q *Queries) IncrementTaskAttempts(ctx context.Context, arg IncrementTaskAttemptsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, incrementTaskAttempts, arg.UpdatedAt, arg.ID)
	var attempts int64
	err := row.Scan(&attempts)
	return attempts, err
}

const insertApprovalToken = `-- name: InsertApprovalToken :exec
INSERT INTO approval_tokens (token_hash, task_id, trace_id, tool, class, scope, approved_bytes_hash, minted_at, expires_at, consumed_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, NULL)
`

type InsertApprovalTokenParams struct {
	TokenHash         string `json:"token_hash"`
	TaskID            string `json:"task_id"`
	TraceID           string `json:"trace_id"`
	Tool              string `json:"tool"`
	Class             string `json:"class"`
	Scope             string `json:"scope"`
	ApprovedBytesHash string `json:"approved_bytes_hash"`
	MintedAt          string `json:"minted_at"`
	ExpiresAt         string `json:"expires_at"`
}

// consumed_at starts NULL (a literal, not a param - see
// ConsumeApprovalToken below for the only statement that ever sets it).
// class/scope persist the token's REAL bound identity (post-security-
// review amendment) so a consume-failure demotion can target this exact
// triple, recovered by token_hash - never whatever (tool,class,scope) the
// /policy/consume-token caller happens to claim.
func (q *Queries) InsertApprovalToken(ctx context.Context, arg InsertApprovalTokenParams) error {
	_, err := q.db.ExecContext(ctx, insertApprovalToken,
		arg.TokenHash,
		arg.TaskID,
		arg.TraceID,
		arg.Tool,
		arg.Class,
		arg.Scope,
		arg.ApprovedBytesHash,
		arg.MintedAt,
		arg.ExpiresAt,
	)
	return err
}

const insertAutonomyState = `-- name: InsertAutonomyState :exec
INSERT INTO autonomy_state (tool, class, scope, level, consecutive_approvals, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertAutonomyStateParams struct {
	Tool                 string `json:"tool"`
	Class                string `json:"class"`
	Scope                string `json:"scope"`
	Level                int64  `json:"level"`
	ConsecutiveApprovals int64  `json:"consecutive_approvals"`
	UpdatedAt            string `json:"updated_at"`
}

func (q *Queries) InsertAutonomyState(ctx context.Context, arg InsertAutonomyStateParams) error {
	_, err := q.db.ExecContext(ctx, insertAutonomyState,
		arg.Tool,
		arg.Class,
		arg.Scope,
		arg.Level,
		arg.ConsecutiveApprovals,
		arg.UpdatedAt,
	)
	return err
}

const insertChunk = `-- name: InsertChunk :one
INSERT INTO chunks (episode_id, seq, text, content_hash, created_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, episode_id, seq, text, content_hash, created_at
`

type InsertChunkParams struct {
	EpisodeID   int64  `json:"episode_id"`
	Seq         int64  `json:"seq"`
	Text        string `json:"text"`
	ContentHash string `json:"content_hash"`
	CreatedAt   string `json:"created_at"`
}

func (q *Queries) InsertChunk(ctx context.Context, arg InsertChunkParams) (Chunk, error) {
	row := q.db.QueryRowContext(ctx, insertChunk,
		arg.EpisodeID,
		arg.Seq,
		arg.Text,
		arg.ContentHash,
		arg.CreatedAt,
	)
	var i Chunk
	err := row.Scan(
		&i.ID,
		&i.EpisodeID,
		&i.Seq,
		&i.Text,
		&i.ContentHash,
		&i.CreatedAt,
	)
	return i, err
}

const insertEgressBudget = `-- name: InsertEgressBudget :exec
INSERT INTO egress_budget (host, day, bytes) VALUES (?, ?, ?)
`

type InsertEgressBudgetParams struct {
	Host  string `json:"host"`
	Day   string `json:"day"`
	Bytes int64  `json:"bytes"`
}

func (q *Queries) InsertEgressBudget(ctx context.Context, arg InsertEgressBudgetParams) error {
	_, err := q.db.ExecContext(ctx, insertEgressBudget, arg.Host, arg.Day, arg.Bytes)
	return err
}

const insertEpisode = `-- name: InsertEpisode :one
INSERT INTO episodes (source, source_path, source_hash, source_tier, started_at, ended_at, status, meta, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, source, source_path, source_hash, source_tier, started_at, ended_at, status, meta, created_at
`

type InsertEpisodeParams struct {
	Source     string         `json:"source"`
	SourcePath sql.NullString `json:"source_path"`
	SourceHash sql.NullString `json:"source_hash"`
	SourceTier string         `json:"source_tier"`
	StartedAt  sql.NullString `json:"started_at"`
	EndedAt    sql.NullString `json:"ended_at"`
	Status     string         `json:"status"`
	Meta       sql.NullString `json:"meta"`
	CreatedAt  string         `json:"created_at"`
}

func (q *Queries) InsertEpisode(ctx context.Context, arg InsertEpisodeParams) (Episode, error) {
	row := q.db.QueryRowContext(ctx, insertEpisode,
		arg.Source,
		arg.SourcePath,
		arg.SourceHash,
		arg.SourceTier,
		arg.StartedAt,
		arg.EndedAt,
		arg.Status,
		arg.Meta,
		arg.CreatedAt,
	)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.SourcePath,
		&i.SourceHash,
		&i.SourceTier,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
		&i.Meta,
		&i.CreatedAt,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :one

INSERT INTO events (trace_id, ts, kind, payload, created_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, trace_id, ts, kind, payload, created_at
`

type InsertEventParams struct {
	TraceID   string `json:"trace_id"`
	Ts        string `json:"ts"`
	Kind      string `json:"kind"`
	Payload   string `json:"payload"`
	CreatedAt string `json:"created_at"`
}

// Starter query set for W12-02 (HANDOFF S4: Go + sqlc-generated queries).
// Later tasks add more queries to this file as they need them; sqlc
// regenerates the whole package from the union of every *.sql file here.
func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, insertEvent,
		arg.TraceID,
		arg.Ts,
		arg.Kind,
		arg.Payload,
		arg.CreatedAt,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.TraceID,
		&i.Ts,
		&i.Kind,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const insertOutboxRow = `-- name: InsertOutboxRow :one

INSERT INTO outbox (trace_id, kind, payload, dispatched_at, created_at, available_at, lease_until, attempts)
VALUES (?, ?, ?, NULL, ?, ?, NULL, 0)
RETURNING id, trace_id, kind, payload, dispatched_at, created_at, available_at, lease_until, attempts
`

type InsertOutboxRowParams struct {
	TraceID     string         `json:"trace_id"`
	Kind        string         `json:"kind"`
	Payload     string         `json:"payload"`
	CreatedAt   string         `json:"created_at"`
	AvailableAt sql.NullString `json:"available_at"`
}

// W4-02 outbox lease/redelivery queries. See migrations/
// 0007_task_durability.sql for the added columns and
// kahyad/internal/outbox/dispatcher.go for the only caller.
// available_at defaults to "now" (immediately dispatchable); lease_until
// starts NULL (never claimed) and attempts starts 0 - both only ever
// change via ClaimOutboxRow below.
func (q *Queries) InsertOutboxRow(ctx context.Context, arg InsertOutboxRowParams) (Outbox, error) {
	row := q.db.QueryRowContext(ctx, insertOutboxRow,
		arg.TraceID,
		arg.Kind,
		arg.Payload,
		arg.CreatedAt,
		arg.AvailableAt,
	)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.TraceID,
		&i.Kind,
		&i.Payload,
		&i.DispatchedAt,
		&i.CreatedAt,
		&i.AvailableAt,
		&i.LeaseUntil,
		&i.Attempts,
	)
	return i, err
}

const insertPendingApproval = `-- name: InsertPendingApproval :exec

INSERT INTO pending_approvals (id, task_id, trace_id, tool, class, scope, approved_bytes_hash, minted_at, expires_at, consumed_at, tool_input)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, NULL, ?)
`

type InsertPendingApprovalParams struct {
	ID                string `json:"id"`
	TaskID            string `json:"task_id"`
	TraceID           string `json:"trace_id"`
	Tool              string `json:"tool"`
	Class             string `json:"class"`
	Scope             string `json:"scope"`
	ApprovedBytesHash string `json:"approved_bytes_hash"`
	MintedAt          string `json:"minted_at"`
	ExpiresAt         string `json:"expires_at"`
	ToolInput         []byte `json:"tool_input"`
}

// Post-security-review amendment: pending_approvals queries below back the
// server-issued, single-use pending_approval_id (see
// migrations/0003_autonomy_policy.sql's doc comment - a NEEDS_APPROVAL
// decision used to hand back an unsigned, caller-decodable blob; it is now
// an opaque random id bound to a DB row only kahyad/internal/policy/
// engine.go writes/reads).
// consumed_at starts NULL (a literal, not a param - see
// ConsumePendingApproval below for the only statement that ever sets it).
// tool_input (W3-06) persists the EXACT bytes Engine.Check received, so
// `kahya approvals`/`kahya approve <id>` can render a real WYSIWYE diff,
// not just prove after the fact (via approved_bytes_hash) that nothing
// changed. Listed last (matching the column's physical ALTER-TABLE-added
// position - see 0005_pending_approval_payload.sql) so GetPendingApproval/
// ListUnconsumedPendingApprovals below reuse the PendingApproval model
// type directly instead of sqlc emitting a separate "Row" type for a
// differently-ordered column list.
func (q *Queries) InsertPendingApproval(ctx context.Context, arg InsertPendingApprovalParams) error {
	_, err := q.db.ExecContext(ctx, insertPendingApproval,
		arg.ID,
		arg.TaskID,
		arg.TraceID,
		arg.Tool,
		arg.Class,
		arg.Scope,
		arg.ApprovedBytesHash,
		arg.MintedAt,
		arg.ExpiresAt,
		arg.ToolInput,
	)
	return err
}

const insertSessionTaintClean = `-- name: InsertSessionTaintClean :exec
INSERT INTO session_taint (session_id, tier, reason, updated_at)
VALUES (?, 'clean', NULL, ?)
`

type InsertSessionTaintCleanParams struct {
	SessionID string `json:"session_id"`
	UpdatedAt string `json:"updated_at"`
}

// The ONLY way a 'clean' row is ever created (task spec step 1): a plain
// INSERT, never an upsert - a session_id that already has ANY row (clean
// or tainted) makes this fail on the PRIMARY KEY constraint, which
// kahyad/internal/taint.Tracker.InsertClean treats as a "lowering
// attempt" (ledgered taint.lower_attempt, rejected) rather than silently
// overwriting an existing row. reason is always NULL for a clean insert -
// there is nothing to explain about a session starting clean, unlike
// RaiseSessionTaint below.
func (q *Queries) InsertSessionTaintClean(ctx context.Context, arg InsertSessionTaintCleanParams) error {
	_, err := q.db.ExecContext(ctx, insertSessionTaintClean, arg.SessionID, arg.UpdatedAt)
	return err
}

const insertTask = `-- name: InsertTask :one
INSERT INTO tasks (id, trace_id, session_id, state, taint_tier, model, envelope, updated_at, created_at, lane, secret_category)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, trace_id, session_id, state, taint_tier, model, envelope, updated_at, created_at, lane, secret_category, status, next_retry_at, attempts
`

type InsertTaskParams struct {
	ID             string         `json:"id"`
	TraceID        string         `json:"trace_id"`
	SessionID      sql.NullString `json:"session_id"`
	State          string         `json:"state"`
	TaintTier      string         `json:"taint_tier"`
	Model          sql.NullString `json:"model"`
	Envelope       sql.NullString `json:"envelope"`
	UpdatedAt      string         `json:"updated_at"`
	CreatedAt      string         `json:"created_at"`
	Lane           string         `json:"lane"`
	SecretCategory sql.NullString `json:"secret_category"`
}

// lane/secret_category (W3-08): the caller ALREADY knows this task's
// secret-lane verdict before this row is ever created (kahyad/internal/
// server's POST /v1/task handler runs kahyad/internal/secretlane's
// classifier BEFORE calling InsertTask - the ordering invariant, HANDOFF
// S4 flag - so there is no window where a task row exists with an
// unclassified lane). The RETURNING clause lists every physical column
// (including status/next_retry_at/attempts, W4-02's 0007_task_durability
// ALTER TABLEs - left OUT of the INSERT column/VALUES list itself, so
// every existing caller keeps inserting a row that takes their DEFAULTs
// unchanged: status='intent', attempts=0, next_retry_at=NULL) so sqlc
// reuses the existing Task model type here rather than generating a
// second, differently-ordered InsertTaskRow type.
func (q *Queries) InsertTask(ctx context.Context, arg InsertTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, insertTask,
		arg.ID,
		arg.TraceID,
		arg.SessionID,
		arg.State,
		arg.TaintTier,
		arg.Model,
		arg.Envelope,
		arg.UpdatedAt,
		arg.CreatedAt,
		arg.Lane,
		arg.SecretCategory,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TraceID,
		&i.SessionID,
		&i.State,
		&i.TaintTier,
		&i.Model,
		&i.Envelope,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Lane,
		&i.SecretCategory,
		&i.Status,
		&i.NextRetryAt,
		&i.Attempts,
	)
	return i, err
}

const insertToolCallIntent = `-- name: InsertToolCallIntent :one
INSERT INTO tool_calls (task_id, seq, tool_name, class, args_hash, approval_token_id, status, receipt_json, started_at, finished_at, created_at)
VALUES (?, ?, ?, ?, ?, ?, 'intent', NULL, NULL, NULL, ?)
RETURNING id, task_id, seq, tool_name, class, args_hash, approval_token_id, status, receipt_json, started_at, finished_at, created_at
`

type InsertToolCallIntentParams struct {
	TaskID          string         `json:"task_id"`
	Seq             int64          `json:"seq"`
	ToolName        string         `json:"tool_name"`
	Class           string         `json:"class"`
	ArgsHash        string         `json:"args_hash"`
	ApprovalTokenID sql.NullString `json:"approval_token_id"`
	CreatedAt       string         `json:"created_at"`
}

// Step 1 of the intent -> executing -> {receipt, failed} lifecycle
// (kahyad/internal/task.Receipts.Execute): one row per side-effectful
// (W1/W2/W3) tool-call ATTEMPT - seq lets the SAME (task_id, tool_name,
// args_hash) triple be re-attempted (a fresh row at a higher seq) after an
// earlier attempt at that exact triple was marked 'failed' by the resume
// scan, while the idempotent-replay lookup (GetReceiptToolCall below)
// only ever matches an attempt that reached 'receipt'.
func (q *Queries) InsertToolCallIntent(ctx context.Context, arg InsertToolCallIntentParams) (ToolCall, error) {
	row := q.db.QueryRowContext(ctx, insertToolCallIntent,
		arg.TaskID,
		arg.Seq,
		arg.ToolName,
		arg.Class,
		arg.ArgsHash,
		arg.ApprovalTokenID,
		arg.CreatedAt,
	)
	var i ToolCall
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Seq,
		&i.ToolName,
		&i.Class,
		&i.ArgsHash,
		&i.ApprovalTokenID,
		&i.Status,
		&i.ReceiptJson,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertUndoWindow = `-- name: InsertUndoWindow :one
INSERT INTO undo_windows (task_id, tool, trace_id, opened_at, deadline, state)
VALUES (?, ?, ?, ?, ?, 'open')
RETURNING id, task_id, tool, trace_id, opened_at, deadline, state
`

type InsertUndoWindowParams struct {
	TaskID   string `json:"task_id"`
	Tool     string `json:"tool"`
	TraceID  string `json:"trace_id"`
	OpenedAt string `json:"opened_at"`
	Deadline string `json:"deadline"`
}

func (q *Queries) InsertUndoWindow(ctx context.Context, arg InsertUndoWindowParams) (UndoWindow, error) {
	row := q.db.QueryRowContext(ctx, insertUndoWindow,
		arg.TaskID,
		arg.Tool,
		arg.TraceID,
		arg.OpenedAt,
		arg.Deadline,
	)
	var i UndoWindow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Tool,
		&i.TraceID,
		&i.OpenedAt,
		&i.Deadline,
		&i.State,
	)
	return i, err
}

const listActiveMemoryFileEpisodes = `-- name: ListActiveMemoryFileEpisodes :many
SELECT id, source_path FROM episodes
WHERE source = 'memory_file' AND status = 'active'
`

type ListActiveMemoryFileEpisodesRow struct {
	ID         int64          `json:"id"`
	SourcePath sql.NullString `json:"source_path"`
}

func (q *Queries) ListActiveMemoryFileEpisodes(ctx context.Context) ([]ListActiveMemoryFileEpisodesRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveMemoryFileEpisodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveMemoryFileEpisodesRow{}
	for rows.Next() {
		var i ListActiveMemoryFileEpisodesRow
		if err := rows.Scan(&i.ID, &i.SourcePath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAutonomyState = `-- name: ListAutonomyState :many
SELECT tool, class, scope, level, consecutive_approvals, updated_at
FROM autonomy_state
ORDER BY tool, class, scope
`

func (q *Queries) ListAutonomyState(ctx context.Context) ([]AutonomyState, error) {
	rows, err := q.db.QueryContext(ctx, listAutonomyState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AutonomyState{}
	for rows.Next() {
		var i AutonomyState
		if err := rows.Scan(
			&i.Tool,
			&i.Class,
			&i.Scope,
			&i.Level,
			&i.ConsecutiveApprovals,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChunkIDsByEpisode = `-- name: ListChunkIDsByEpisode :many
SELECT id FROM chunks WHERE episode_id = ? ORDER BY seq ASC
`

func (q *Queries) ListChunkIDsByEpisode(ctx context.Context, episodeID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listChunkIDsByEpisode, episodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueOutboxRows = `-- name: ListDueOutboxRows :many
SELECT id, trace_id, kind, payload, dispatched_at, created_at, available_at, lease_until, attempts
FROM outbox
WHERE dispatched_at IS NULL
  AND available_at <= ?
  AND (lease_until IS NULL OR lease_until < ?)
ORDER BY id ASC
LIMIT ?
`

type ListDueOutboxRowsParams struct {
	AvailableAt sql.NullString `json:"available_at"`
	LeaseUntil  sql.NullString `json:"lease_until"`
	Limit       int64          `json:"limit"`
}

// Candidate rows for one dispatcher claim pass: not yet delivered,
// available (available_at <= now), and not currently leased by another
// dispatcher (lease_until IS NULL, i.e. never claimed, OR lease_until has
// already passed, i.e. a previous claim's lease expired without being
// acknowledged - the crash-safe re-claim path). Listing candidates and
// claiming them are two separate steps ON PURPOSE (ClaimOutboxRow below)
// so two concurrent dispatchers racing on the SAME candidate list each
// only ever win the atomic UPDATE for rows the other hasn't already
// claimed first.
func (q *Queries) ListDueOutboxRows(ctx context.Context, arg ListDueOutboxRowsParams) ([]Outbox, error) {
	rows, err := q.db.QueryContext(ctx, listDueOutboxRows, arg.AvailableAt, arg.LeaseUntil, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Outbox{}
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.TraceID,
			&i.Kind,
			&i.Payload,
			&i.DispatchedAt,
			&i.CreatedAt,
			&i.AvailableAt,
			&i.LeaseUntil,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByKind = `-- name: ListEventsByKind :many
SELECT id, trace_id, ts, kind, payload, created_at
FROM events
WHERE kind = ?
ORDER BY id ASC
`

// W12-08 (anthproxy cost governor): boot-time rebuild reads every
// historical event of one kind (e.g. 'model_call') and replays it into
// the in-memory governor totals - kahyad/internal/anthproxy stays
// store-agnostic (it never imports this package); main.go converts each
// row into an anthproxy.BootEvent.
func (q *Queries) ListEventsByKind(ctx context.Context, kind string) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByKind, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.TraceID,
			&i.Ts,
			&i.Kind,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByTrace = `-- name: ListEventsByTrace :many
SELECT id, trace_id, ts, kind, payload, created_at
FROM events
WHERE trace_id = ?
ORDER BY id ASC
`

func (q *Queries) ListEventsByTrace(ctx context.Context, traceID string) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByTrace, traceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.TraceID,
			&i.Ts,
			&i.Kind,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExecutingTasks = `-- name: ListExecutingTasks :many
SELECT id, trace_id, session_id, state, taint_tier, model, envelope, updated_at, created_at, lane, secret_category, status, next_retry_at, attempts
FROM tasks
WHERE status = 'executing'
ORDER BY updated_at ASC
`

// The resume scan's candidate set (kahyad startup + periodic tick):
// every task currently recorded as 'executing'. kahyad/internal/task's
// own LiveRegistry then filters this down to the ones with NO live worker
// PID - a live task is simply skipped (the daemon itself is still running
// it).
func (q *Queries) ListExecutingTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listExecutingTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TraceID,
			&i.SessionID,
			&i.State,
			&i.TaintTier,
			&i.Model,
			&i.Envelope,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.Lane,
			&i.SecretCategory,
			&i.Status,
			&i.NextRetryAt,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenUndoWindows = `-- name: ListOpenUndoWindows :many
SELECT id, task_id, tool, trace_id, opened_at, deadline, state
FROM undo_windows
WHERE state = 'open'
`

func (q *Queries) ListOpenUndoWindows(ctx context.Context) ([]UndoWindow, error) {
	rows, err := q.db.QueryContext(ctx, listOpenUndoWindows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UndoWindow{}
	for rows.Next() {
		var i UndoWindow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Tool,
			&i.TraceID,
			&i.OpenedAt,
			&i.Deadline,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceiptlessToolCalls = `-- name: ListReceiptlessToolCalls :many
SELECT id, task_id, seq, tool_name, class, args_hash, approval_token_id, status, receipt_json, started_at, finished_at, created_at
FROM tool_calls
WHERE task_id = ? AND status IN ('intent', 'executing')
ORDER BY id DESC
`

// Every tool_calls row for task_id still stuck at 'intent'/'executing' -
// i.e. a side-effectful call whose kahyad-side execution was interrupted
// (worker died, kahyad crashed) before a receipt (or a failure) was ever
// recorded. Ordered most-recent-first: the resume scan (task spec step 6)
// only ever needs the single most recent one - realistically there is at
// most one such row per task at any moment, but the scan itself is
// defensive about that.
func (q *Queries) ListReceiptlessToolCalls(ctx context.Context, taskID string) ([]ToolCall, error) {
	rows, err := q.db.QueryContext(ctx, listReceiptlessToolCalls, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ToolCall{}
	for rows.Next() {
		var i ToolCall
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Seq,
			&i.ToolName,
			&i.Class,
			&i.ArgsHash,
			&i.ApprovalTokenID,
			&i.Status,
			&i.ReceiptJson,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToolCallsByTask = `-- name: ListToolCallsByTask :many
SELECT id, task_id, seq, tool_name, class, args_hash, approval_token_id, status, receipt_json, started_at, finished_at, created_at
FROM tool_calls
WHERE task_id = ?
ORDER BY seq ASC, id ASC
`

// `kahya task show <id>`'s tool_calls listing, oldest attempt first.
func (q *Queries) ListToolCallsByTask(ctx context.Context, taskID string) ([]ToolCall, error) {
	rows, err := q.db.QueryContext(ctx, listToolCallsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ToolCall{}
	for rows.Next() {
		var i ToolCall
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Seq,
			&i.ToolName,
			&i.Class,
			&i.ArgsHash,
			&i.ApprovalTokenID,
			&i.Status,
			&i.ReceiptJson,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnconsumedPendingApprovals = `-- name: ListUnconsumedPendingApprovals :many
SELECT id, task_id, trace_id, tool, class, scope, approved_bytes_hash, minted_at, expires_at, consumed_at, tool_input
FROM pending_approvals
WHERE consumed_at IS NULL
ORDER BY minted_at ASC
`

// W3-06 `kahya approvals`: every not-yet-consumed row, oldest first.
// Expiry is checked in Go (kahyad/internal/policy.Engine.ListPendingApprovals),
// mirroring getValidPendingApproval's own time.Parse+time.After check,
// rather than comparing RFC3339Nano strings in SQL (that format's
// trailing-zero-trimmed fractional seconds do NOT always sort
// lexicographically in timestamp order).
func (q *Queries) ListUnconsumedPendingApprovals(ctx context.Context) ([]PendingApproval, error) {
	rows, err := q.db.QueryContext(ctx, listUnconsumedPendingApprovals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingApproval{}
	for rows.Next() {
		var i PendingApproval
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.TraceID,
			&i.Tool,
			&i.Class,
			&i.Scope,
			&i.ApprovedBytesHash,
			&i.MintedAt,
			&i.ExpiresAt,
			&i.ConsumedAt,
			&i.ToolInput,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEpisodeDeleted = `-- name: MarkEpisodeDeleted :exec
UPDATE episodes
SET status = 'deleted'
WHERE id = ?
`

func (q *Queries) MarkEpisodeDeleted(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markEpisodeDeleted, id)
	return err
}

const markOutboxDelivered = `-- name: MarkOutboxDelivered :exec
UPDATE outbox
SET dispatched_at = ?
WHERE id = ?
`

type MarkOutboxDeliveredParams struct {
	DispatchedAt sql.NullString `json:"dispatched_at"`
	ID           int64          `json:"id"`
}

// Terminal success: the re-spawned worker exited 0 (task spec step 7).
func (q *Queries) MarkOutboxDelivered(ctx context.Context, arg MarkOutboxDeliveredParams) error {
	_, err := q.db.ExecContext(ctx, markOutboxDelivered, arg.DispatchedAt, arg.ID)
	return err
}

const markToolCallExecuting = `-- name: MarkToolCallExecuting :exec
UPDATE tool_calls
SET status = 'executing', started_at = ?
WHERE id = ?
`

type MarkToolCallExecutingParams struct {
	StartedAt sql.NullString `json:"started_at"`
	ID        int64          `json:"id"`
}

func (q *Queries) MarkToolCallExecuting(ctx context.Context, arg MarkToolCallExecutingParams) error {
	_, err := q.db.ExecContext(ctx, markToolCallExecuting, arg.StartedAt, arg.ID)
	return err
}

const markToolCallFailed = `-- name: MarkToolCallFailed :exec
UPDATE tool_calls
SET status = 'failed', finished_at = ?
WHERE id = ?
`

type MarkToolCallFailedParams struct {
	FinishedAt sql.NullString `json:"finished_at"`
	ID         int64          `json:"id"`
}

// Used both when a tool's own effect function returns an error (genuine
// execution failure) AND by the resume scan, which marks a receipt-less
// 'intent'/'executing' row 'failed' before deciding whether to auto-retry
// (W1, within cap) or escalate to blocked_user (W1 past cap, or any
// W2/W3).
func (q *Queries) MarkToolCallFailed(ctx context.Context, arg MarkToolCallFailedParams) error {
	_, err := q.db.ExecContext(ctx, markToolCallFailed, arg.FinishedAt, arg.ID)
	return err
}

const markToolCallReceipt = `-- name: MarkToolCallReceipt :exec
UPDATE tool_calls
SET status = 'receipt', receipt_json = ?, finished_at = ?
WHERE id = ?
`

type MarkToolCallReceiptParams struct {
	ReceiptJson sql.NullString `json:"receipt_json"`
	FinishedAt  sql.NullString `json:"finished_at"`
	ID          int64          `json:"id"`
}

// The terminal success state: receipt_json (result + result hash) is
// written in the SAME database transaction that commits the tool's own
// DB-side effects, immediately once the side effect completes (task spec
// step 3) - kahyad/internal/task.Receipts.Execute runs this inside the
// same *sql.Tx as the caller-supplied effect function whenever that
// effect writes to brain.db itself.
func (q *Queries) MarkToolCallReceipt(ctx context.Context, arg MarkToolCallReceiptParams) error {
	_, err := q.db.ExecContext(ctx, markToolCallReceipt, arg.ReceiptJson, arg.FinishedAt, arg.ID)
	return err
}

const nextToolCallSeq = `-- name: NextToolCallSeq :one
SELECT COALESCE(MAX(seq), 0) + 1 FROM tool_calls WHERE task_id = ? AND tool_name = ? AND args_hash = ?
`

type NextToolCallSeqParams struct {
	TaskID   string `json:"task_id"`
	ToolName string `json:"tool_name"`
	ArgsHash string `json:"args_hash"`
}

// The next seq value for a (task_id, tool_name, args_hash) triple (1 for a
// never-attempted triple).
func (q *Queries) NextToolCallSeq(ctx context.Context, arg NextToolCallSeqParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextToolCallSeq, arg.TaskID, arg.ToolName, arg.ArgsHash)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const raiseSessionTaint = `-- name: RaiseSessionTaint :exec
INSERT INTO session_taint (session_id, tier, reason, updated_at)
VALUES (?, 'tainted', ?, ?)
ON CONFLICT (session_id) DO UPDATE SET
    tier = 'tainted',
    reason = excluded.reason,
    updated_at = excluded.updated_at
`

type RaiseSessionTaintParams struct {
	SessionID string         `json:"session_id"`
	Reason    sql.NullString `json:"reason"`
	UpdatedAt string         `json:"updated_at"`
}

// The ONLY tier-transition statement in this file: upserts session_id to
// tier='tainted', creating the row if it did not exist yet (a
// content-sourced tool output can raise taint on a session before that
// session's OWN 'clean' row ever landed - the ordering invariant is "no
// byte reaches the worker before this Raise call", not "the row must
// already exist") or flipping an existing 'clean' row to 'tainted' (and
// leaving an already-'tainted' row at 'tainted', updating reason/
// updated_at regardless - taint only ever rises, so re-raising a
// different reason is fine, re-raising the SAME tier is a no-op by
// definition). There is no corresponding statement anywhere in this
// codebase that ever sets tier back to 'clean' on an existing row.
func (q *Queries) RaiseSessionTaint(ctx context.Context, arg RaiseSessionTaintParams) error {
	_, err := q.db.ExecContext(ctx, raiseSessionTaint, arg.SessionID, arg.Reason, arg.UpdatedAt)
	return err
}

const renewOutboxLease = `-- name: RenewOutboxLease :exec
UPDATE outbox
SET lease_until = ?
WHERE id = ? AND dispatched_at IS NULL
`

type RenewOutboxLeaseParams struct {
	LeaseUntil sql.NullString `json:"lease_until"`
	ID         int64          `json:"id"`
}

// Task durability BLOCKER 2(b) fix: kahyad/internal/outbox.Dispatcher's
// heartbeat goroutine calls this every leaseDuration/3 for as long as
// spawn.Run blocks on a claimed row's re-spawned worker, so a
// longer-than-one-lease-period task is never re-claimed by a second
// dispatcher pass purely because its ORIGINAL lease (computed once at
// claim time) elapsed while the worker was still genuinely running.
// Scoped to dispatched_at IS NULL defensively - a row this dispatcher has
// already marked delivered (or that somehow no longer exists) must never
// have its lease resurrected.
func (q *Queries) RenewOutboxLease(ctx context.Context, arg RenewOutboxLeaseParams) error {
	_, err := q.db.ExecContext(ctx, renewOutboxLease, arg.LeaseUntil, arg.ID)
	return err
}

const setTaskLane = `-- name: SetTaskLane :exec

UPDATE tasks
SET lane = ?, secret_category = ?, updated_at = ?
WHERE id = ?
`

type SetTaskLaneParams struct {
	Lane           string         `json:"lane"`
	SecretCategory sql.NullString `json:"secret_category"`
	UpdatedAt      string         `json:"updated_at"`
	ID             string         `json:"id"`
}

// W3-08 (secret-lane routing) queries below: lane/secret_category are
// STICKY (kahyad/internal/secretlane.Escalate enforces "only ever widens,
// never downgrades" in Go, not SQL - see 0006_secret_lane.sql's own doc
// comment). kahyad/internal/secretlane.NewProxyBackstopHook (the W12-08
// proxy chokepoint) is GetTaskLane's other caller, consulted on EVERY
// forwarded model-call request.
func (q *Queries) SetTaskLane(ctx context.Context, arg SetTaskLaneParams) error {
	_, err := q.db.ExecContext(ctx, setTaskLane,
		arg.Lane,
		arg.SecretCategory,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const setTaskStatus = `-- name: SetTaskStatus :execrows
UPDATE tasks
SET status = ?, updated_at = ?
WHERE id = ? AND status = ?
`

type SetTaskStatusParams struct {
	Status    string `json:"status"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
	Status_2  string `json:"status_2"`
}

// The ONLY writer of tasks.status is kahyad/internal/task.Machine.Transition
// - every status change is preceded by that function's own legal-transition
// check and followed by a task.transition (or task.illegal_transition)
// ledger event; this query performs no validation of its own.
//
// task durability BLOCKER 3 fix: the WHERE clause's own "status = ?" (the
// FROM status Machine.Transition just read via GetTaskByID) makes this an
// atomic compare-and-set, not a blind write - two concurrent Transition
// calls racing from the SAME stale 'from' read can now only ever have ONE
// of them actually affect a row (rows-affected 1); the loser affects 0
// rows (its 'from' no longer matches - some other transition already won)
// and Machine.Transition treats that as a lost race, never silently
// overwriting whatever the winner just wrote (no more last-write-wins).
func (q *Queries) SetTaskStatus(ctx context.Context, arg SetTaskStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setTaskStatus,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
		arg.Status_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setUndoWindowState = `-- name: SetUndoWindowState :exec
UPDATE undo_windows
SET state = ?
WHERE id = ?
`

type SetUndoWindowStateParams struct {
	State string `json:"state"`
	ID    int64  `json:"id"`
}

func (q *Queries) SetUndoWindowState(ctx context.Context, arg SetUndoWindowStateParams) error {
	_, err := q.db.ExecContext(ctx, setUndoWindowState, arg.State, arg.ID)
	return err
}

const updateAutonomyState = `-- name: UpdateAutonomyState :execrows
UPDATE autonomy_state
SET level = ?, consecutive_approvals = ?, updated_at = ?
WHERE tool = ? AND class = ? AND scope = ?
`

type UpdateAutonomyStateParams struct {
	Level                int64  `json:"level"`
	ConsecutiveApprovals int64  `json:"consecutive_approvals"`
	UpdatedAt            string `json:"updated_at"`
	Tool                 string `json:"tool"`
	Class                string `json:"class"`
	Scope                string `json:"scope"`
}

// Update-half of an application-level upsert (kahyad/internal/policy
// calls this first; a 0-rows-affected result means no row exists yet, so
// it falls back to InsertAutonomyState - the same "upsert (update half)"
// pattern UpdateEpisodeContent above already uses in this file).
func (q *Queries) UpdateAutonomyState(ctx context.Context, arg UpdateAutonomyStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAutonomyState,
		arg.Level,
		arg.ConsecutiveApprovals,
		arg.UpdatedAt,
		arg.Tool,
		arg.Class,
		arg.Scope,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateEpisodeContent = `-- name: UpdateEpisodeContent :exec
UPDATE episodes
SET source_hash = ?, source_tier = ?, status = ?
WHERE id = ?
`

type UpdateEpisodeContentParams struct {
	SourceHash sql.NullString `json:"source_hash"`
	SourceTier string         `json:"source_tier"`
	Status     string         `json:"status"`
	ID         int64          `json:"id"`
}

// Upserts (update half) an existing memory_file episode in place on
// new/changed content: same id, fresh hash/tier, status forced back to
// 'active' (covers the resurrect-a-deleted-file case, not just plain edits).
func (q *Queries) UpdateEpisodeContent(ctx context.Context, arg UpdateEpisodeContentParams) error {
	_, err := q.db.ExecContext(ctx, updateEpisodeContent,
		arg.SourceHash,
		arg.SourceTier,
		arg.Status,
		arg.ID,
	)
	return err
}

const updateTaskSession = `-- name: UpdateTaskSession :exec
UPDATE tasks
SET session_id = ?, updated_at = ?
WHERE id = ?
`

type UpdateTaskSessionParams struct {
	SessionID sql.NullString `json:"session_id"`
	UpdatedAt string         `json:"updated_at"`
	ID        string         `json:"id"`
}

// Persists a worker-reported session_id onto the task row (W12-07 step 3:
// kahyad "persists session_id onto the task row" as the worker's
// {"type":"session",...} stdout line arrives). Session RESUME itself
// (using a stored session_id to continue a LATER task) is W4-02; this
// query only records the value as it arrives.
func (q *Queries) UpdateTaskSession(ctx context.Context, arg UpdateTaskSessionParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskSession, arg.SessionID, arg.UpdatedAt, arg.ID)
	return err
}

const updateTaskState = `-- name: UpdateTaskState :exec
UPDATE tasks
SET state = ?, updated_at = ?
WHERE id = ?
`

type UpdateTaskStateParams struct {
	State     string `json:"state"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateTaskState(ctx context.Context, arg UpdateTaskStateParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskState, arg.State, arg.UpdatedAt, arg.ID)
	return err
}
