-- 0001_init_schema: brain.db Day-1 schema (HANDOFF S5, mandatory table
-- list). kahyad is the ONLY writer of this database (HANDOFF S4/S5);
-- every table below must exist from day 1 even though most start empty -
-- the evidence<->episode/session link is capture-moment data that cannot
-- be derived later.
--
-- All ids are surrogate keys; every table also carries created_at
-- (RFC3339 UTC) for a uniform audit trail, in addition to any
-- domain-specific timestamp columns (started_at/ended_at, updated_at, ts,
-- dispatched_at, ...).
--
-- NOTE on facts.confidence: this column stores LOG-ODDS
-- (ln(p/(1-p))), NOT a bare probability. It is a REAL and CAN be
-- negative (0 == p=0.5); never write a 0..1 probability into it directly.
--
-- NOTE: keep this file (and kahyad/internal/store/queries/*.sql) plain
-- ASCII. sqlc's sqlite parser (v1.30.0) mis-locates statement boundaries
-- when a multi-byte UTF-8 rune appears in a .sql file it parses, silently
-- truncating the tail of unrelated generated query strings a few bytes
-- short (confirmed empirically: a single non-ASCII byte in queries.sql was
-- enough to corrupt every generated query in this repo's sqlc.yaml) - use
-- "S5"/"->"/plain transliterations instead of section signs, flags,
-- em-dashes, etc.

-- +goose Up
CREATE TABLE episodes (
    id          INTEGER PRIMARY KEY,
    source      TEXT NOT NULL,
    source_path TEXT,
    source_hash TEXT,
    -- source_tier drives corpus-chunk injection eligibility (W12-05).
    source_tier TEXT NOT NULL DEFAULT 'user_asserted'
                CHECK (source_tier IN ('user_edit', 'user_asserted', 'external_doc', 'screen', 'agent_derived')),
    started_at  TEXT,
    ended_at    TEXT,
    status      TEXT NOT NULL DEFAULT 'active',
    meta        TEXT,
    created_at  TEXT NOT NULL
);

CREATE TABLE chunks (
    id           INTEGER PRIMARY KEY,
    episode_id   INTEGER NOT NULL REFERENCES episodes(id),
    seq          INTEGER NOT NULL,
    text         TEXT NOT NULL,
    content_hash TEXT NOT NULL,
    created_at   TEXT NOT NULL,
    UNIQUE (episode_id, seq)
);

CREATE TABLE facts (
    id            INTEGER PRIMARY KEY,
    subject       TEXT NOT NULL,
    predicate     TEXT NOT NULL,
    object        TEXT NOT NULL,
    source_tier   TEXT NOT NULL
                  CHECK (source_tier IN ('user_edit', 'user_asserted', 'external_doc', 'screen', 'agent_derived')),
    -- evidentiality mirrors the Turkish reported-past (-mis) evidential
    -- suffix: witnessed | reported | inferred.
    evidentiality TEXT NOT NULL CHECK (evidentiality IN ('witnessed', 'reported', 'inferred')),
    -- confidence: LOG-ODDS, REAL, may be negative. See file header note.
    confidence    REAL NOT NULL,
    importance    REAL NOT NULL DEFAULT 0,
    -- Bitemporal (valid_from/valid_to) columns exist from day 1; full
    -- bitemporal graph queries are v2 (HANDOFF S8).
    valid_from    TEXT,
    valid_to      TEXT,
    status        TEXT NOT NULL DEFAULT 'active',
    evidence      TEXT,
    extractor_ver TEXT,
    updated_at    TEXT NOT NULL,
    created_at    TEXT NOT NULL
);

CREATE TABLE entities (
    id             INTEGER PRIMARY KEY,
    canonical_name TEXT NOT NULL,
    kind           TEXT,
    status         TEXT NOT NULL DEFAULT 'active',
    created_at     TEXT NOT NULL
);

CREATE TABLE entity_aliases (
    id         INTEGER PRIMARY KEY,
    entity_id  INTEGER NOT NULL REFERENCES entities(id),
    alias      TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE evidence (
    id         INTEGER PRIMARY KEY,
    fact_id    INTEGER NOT NULL REFERENCES facts(id),
    episode_id INTEGER REFERENCES episodes(id),
    session_id TEXT,
    -- polarity: +1 supports the fact, -1 is negative evidence (HANDOFF S5
    -- memory #3 log-odds ratchet).
    polarity   INTEGER NOT NULL CHECK (polarity IN (-1, 1)),
    created_at TEXT NOT NULL
);

CREATE TABLE merge_ledger (
    id            INTEGER PRIMARY KEY,
    op            TEXT NOT NULL CHECK (op IN ('merge', 'split')),
    src_entity_id INTEGER,
    dst_entity_id INTEGER,
    evidence      TEXT,
    actor         TEXT NOT NULL,
    created_at    TEXT NOT NULL
);

CREATE TABLE tasks (
    -- task ids are minted strings (not rowids) so they can be generated by
    -- the caller before the row exists.
    id         TEXT PRIMARY KEY,
    trace_id   TEXT NOT NULL,
    session_id TEXT,
    state      TEXT NOT NULL,
    -- taint_tier: persisted taint layer keyed by session_id (HANDOFF S5
    -- safety #2). This column only ever rises, never falls; that
    -- monotonicity is enforced in Go (W4-03), not by a SQL constraint,
    -- since it depends on comparing the new value against history.
    taint_tier TEXT NOT NULL DEFAULT 'untrusted',
    model      TEXT,
    envelope   TEXT,
    updated_at TEXT NOT NULL,
    created_at TEXT NOT NULL
);

-- events is the append-only ledger (HANDOFF S4: "defter"). trace_id ties
-- every line back to the JSONL logs (HANDOFF S4 logging invariant).
CREATE TABLE events (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    trace_id   TEXT NOT NULL,
    ts         TEXT NOT NULL,
    kind       TEXT NOT NULL,
    payload    TEXT NOT NULL,
    created_at TEXT NOT NULL
);

-- Append-only enforcement at the SQL level (HANDOFF S5 safety #4): even a
-- bug elsewhere in the codebase can never rewrite or erase ledger history.
-- +goose StatementBegin
CREATE TRIGGER events_no_update
BEFORE UPDATE ON events
BEGIN
    SELECT RAISE(ABORT, 'ledger is append-only');
END;
-- +goose StatementEnd

-- +goose StatementBegin
CREATE TRIGGER events_no_delete
BEFORE DELETE ON events
BEGIN
    SELECT RAISE(ABORT, 'ledger is append-only');
END;
-- +goose StatementEnd

-- outbox: MVP internal data path is "SQLite outbox table + goroutines"
-- (HANDOFF S4 stack); the dispatcher itself is W4-02.
CREATE TABLE outbox (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    trace_id      TEXT NOT NULL,
    kind          TEXT NOT NULL,
    payload       TEXT NOT NULL,
    dispatched_at TEXT,
    created_at    TEXT NOT NULL
);

CREATE INDEX idx_events_trace_id ON events(trace_id);
CREATE INDEX idx_events_kind_ts ON events(kind, ts);
CREATE INDEX idx_chunks_episode_id ON chunks(episode_id);
CREATE INDEX idx_facts_subject ON facts(subject);
CREATE INDEX idx_evidence_fact_id ON evidence(fact_id);
CREATE INDEX idx_tasks_trace_id ON tasks(trace_id);
CREATE INDEX idx_tasks_session_id ON tasks(session_id);

-- +goose Down
DROP INDEX IF EXISTS idx_tasks_session_id;
DROP INDEX IF EXISTS idx_tasks_trace_id;
DROP INDEX IF EXISTS idx_evidence_fact_id;
DROP INDEX IF EXISTS idx_facts_subject;
DROP INDEX IF EXISTS idx_chunks_episode_id;
DROP INDEX IF EXISTS idx_events_kind_ts;
DROP INDEX IF EXISTS idx_events_trace_id;

DROP TABLE IF EXISTS outbox;
DROP TRIGGER IF EXISTS events_no_delete;
DROP TRIGGER IF EXISTS events_no_update;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS merge_ledger;
DROP TABLE IF EXISTS evidence;
DROP TABLE IF EXISTS entity_aliases;
DROP TABLE IF EXISTS entities;
DROP TABLE IF EXISTS facts;
DROP TABLE IF EXISTS chunks;
DROP TABLE IF EXISTS episodes;
